// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atendimentos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarAtendimento = `-- name: AtualizarAtendimento :one
UPDATE atendimentos
SET cliente_nome = $2, descricao = $3, data_atendimento = $4, atualizado_em = now()
WHERE id = $1
RETURNING id, cliente_nome, descricao, data_atendimento, usuario_id, criado_em, atualizado_em
`

type AtualizarAtendimentoParams struct {
	ID              pgtype.UUID        `json:"id"`
	ClienteNome     string             `json:"cliente_nome"`
	Descricao       string             `json:"descricao"`
	DataAtendimento pgtype.Timestamptz `json:"data_atendimento"`
}

func (q *Queries) AtualizarAtendimento(ctx context.Context, arg AtualizarAtendimentoParams) (Atendimentos, error) {
	row := q.db.QueryRow(ctx, atualizarAtendimento,
		arg.ID,
		arg.ClienteNome,
		arg.Descricao,
		arg.DataAtendimento,
	)
	var i Atendimentos
	err := row.Scan(
		&i.ID,
		&i.ClienteNome,
		&i.Descricao,
		&i.DataAtendimento,
		&i.UsuarioID,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarAtendimentoPorID = `-- name: BuscarAtendimentoPorID :one
SELECT 
    a.id, a.cliente_nome, a.descricao, a.data_atendimento, a.usuario_id, a.criado_em, a.atualizado_em,
    u.nome AS usuario_nome, u.cor AS usuario_cor
FROM atendimentos a
JOIN usuarios u ON u.id = a.usuario_id
WHERE a.id = $1
`

type BuscarAtendimentoPorIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	ClienteNome     string             `json:"cliente_nome"`
	Descricao       string             `json:"descricao"`
	DataAtendimento pgtype.Timestamptz `json:"data_atendimento"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
	UsuarioNome     string             `json:"usuario_nome"`
	UsuarioCor      string             `json:"usuario_cor"`
}

func (q *Queries) BuscarAtendimentoPorID(ctx context.Context, id pgtype.UUID) (BuscarAtendimentoPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarAtendimentoPorID, id)
	var i BuscarAtendimentoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.ClienteNome,
		&i.Descricao,
		&i.DataAtendimento,
		&i.UsuarioID,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.UsuarioNome,
		&i.UsuarioCor,
	)
	return i, err
}

const contarAtendimentos = `-- name: ContarAtendimentos :one
SELECT count(*)
FROM atendimentos a
WHERE 
    ($1::text IS NULL OR 
     unaccent(lower(a.cliente_nome)) ILIKE '%' || unaccent(lower($1)) || '%' OR
     unaccent(lower(a.descricao)) ILIKE '%' || unaccent(lower($1)) || '%')
    AND ($2::uuid IS NULL OR a.usuario_id = $2)
    AND ($3::timestamptz IS NULL OR a.data_atendimento >= $3)
    AND ($4::timestamptz IS NULL OR a.data_atendimento <= $4)
`

type ContarAtendimentosParams struct {
	Busca      pgtype.Text        `json:"busca"`
	UsuarioID  pgtype.UUID        `json:"usuario_id"`
	DataInicio pgtype.Timestamptz `json:"data_inicio"`
	DataFim    pgtype.Timestamptz `json:"data_fim"`
}

func (q *Queries) ContarAtendimentos(ctx context.Context, arg ContarAtendimentosParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarAtendimentos,
		arg.Busca,
		arg.UsuarioID,
		arg.DataInicio,
		arg.DataFim,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarAtendimento = `-- name: CriarAtendimento :one
INSERT INTO atendimentos (cliente_nome, descricao, data_atendimento, usuario_id)
VALUES ($1, $2, $3, $4)
RETURNING id, cliente_nome, descricao, data_atendimento, usuario_id, criado_em, atualizado_em
`

type CriarAtendimentoParams struct {
	ClienteNome     string             `json:"cliente_nome"`
	Descricao       string             `json:"descricao"`
	DataAtendimento pgtype.Timestamptz `json:"data_atendimento"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
}

func (q *Queries) CriarAtendimento(ctx context.Context, arg CriarAtendimentoParams) (Atendimentos, error) {
	row := q.db.QueryRow(ctx, criarAtendimento,
		arg.ClienteNome,
		arg.Descricao,
		arg.DataAtendimento,
		arg.UsuarioID,
	)
	var i Atendimentos
	err := row.Scan(
		&i.ID,
		&i.ClienteNome,
		&i.Descricao,
		&i.DataAtendimento,
		&i.UsuarioID,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deletarAtendimento = `-- name: DeletarAtendimento :exec
DELETE FROM atendimentos
WHERE id = $1
`

func (q *Queries) DeletarAtendimento(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarAtendimento, id)
	return err
}

const listarAtendimentos = `-- name: ListarAtendimentos :many
SELECT 
    a.id, a.cliente_nome, a.descricao, a.data_atendimento, a.usuario_id, a.criado_em, a.atualizado_em,
    u.nome AS usuario_nome, u.cor AS usuario_cor
FROM atendimentos a
JOIN usuarios u ON u.id = a.usuario_id
WHERE 
    ($3::text IS NULL OR 
     unaccent(lower(a.cliente_nome)) ILIKE '%' || unaccent(lower($3)) || '%' OR
     unaccent(lower(a.descricao)) ILIKE '%' || unaccent(lower($3)) || '%')
    AND ($4::uuid IS NULL OR a.usuario_id = $4)
    AND ($5::timestamptz IS NULL OR a.data_atendimento >= $5)
    AND ($6::timestamptz IS NULL OR a.data_atendimento <= $6)
ORDER BY a.data_atendimento DESC
LIMIT $1 OFFSET $2
`

type ListarAtendimentosParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	Busca      pgtype.Text        `json:"busca"`
	UsuarioID  pgtype.UUID        `json:"usuario_id"`
	DataInicio pgtype.Timestamptz `json:"data_inicio"`
	DataFim    pgtype.Timestamptz `json:"data_fim"`
}

type ListarAtendimentosRow struct {
	ID              pgtype.UUID        `json:"id"`
	ClienteNome     string             `json:"cliente_nome"`
	Descricao       string             `json:"descricao"`
	DataAtendimento pgtype.Timestamptz `json:"data_atendimento"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
	UsuarioNome     string             `json:"usuario_nome"`
	UsuarioCor      string             `json:"usuario_cor"`
}

func (q *Queries) ListarAtendimentos(ctx context.Context, arg ListarAtendimentosParams) ([]ListarAtendimentosRow, error) {
	rows, err := q.db.Query(ctx, listarAtendimentos,
		arg.Limit,
		arg.Offset,
		arg.Busca,
		arg.UsuarioID,
		arg.DataInicio,
		arg.DataFim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarAtendimentosRow
	for rows.Next() {
		var i ListarAtendimentosRow
		if err := rows.Scan(
			&i.ID,
			&i.ClienteNome,
			&i.Descricao,
			&i.DataAtendimento,
			&i.UsuarioID,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.UsuarioNome,
			&i.UsuarioCor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
