// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: avisos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarAviso = `-- name: AtualizarAviso :one
UPDATE avisos
SET titulo = $2, mensagem = $3, nivel = $4, expira_em = $5, atualizado_em = now()
WHERE id = $1
RETURNING id, titulo, mensagem, nivel, expira_em, criado_por, criado_em, atualizado_em, setor_id
`

type AtualizarAvisoParams struct {
	ID       pgtype.UUID        `json:"id"`
	Titulo   string             `json:"titulo"`
	Mensagem string             `json:"mensagem"`
	Nivel    string             `json:"nivel"`
	ExpiraEm pgtype.Timestamptz `json:"expira_em"`
}

func (q *Queries) AtualizarAviso(ctx context.Context, arg AtualizarAvisoParams) (Avisos, error) {
	row := q.db.QueryRow(ctx, atualizarAviso,
		arg.ID,
		arg.Titulo,
		arg.Mensagem,
		arg.Nivel,
		arg.ExpiraEm,
	)
	var i Avisos
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Mensagem,
		&i.Nivel,
		&i.ExpiraEm,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const criarAviso = `-- name: CriarAviso :one
INSERT INTO avisos (titulo, mensagem, nivel, expira_em, criado_por, setor_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, titulo, mensagem, nivel, expira_em, criado_por, criado_em, atualizado_em, setor_id
`

type CriarAvisoParams struct {
	Titulo    string             `json:"titulo"`
	Mensagem  string             `json:"mensagem"`
	Nivel     string             `json:"nivel"`
	ExpiraEm  pgtype.Timestamptz `json:"expira_em"`
	CriadoPor pgtype.UUID        `json:"criado_por"`
	SetorID   pgtype.UUID        `json:"setor_id"`
}

func (q *Queries) CriarAviso(ctx context.Context, arg CriarAvisoParams) (Avisos, error) {
	row := q.db.QueryRow(ctx, criarAviso,
		arg.Titulo,
		arg.Mensagem,
		arg.Nivel,
		arg.ExpiraEm,
		arg.CriadoPor,
		arg.SetorID,
	)
	var i Avisos
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Mensagem,
		&i.Nivel,
		&i.ExpiraEm,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const deletarAviso = `-- name: DeletarAviso :exec
DELETE FROM avisos WHERE id = $1
`

func (q *Queries) DeletarAviso(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarAviso, id)
	return err
}

const listarAvisosAtivos = `-- name: ListarAvisosAtivos :many
SELECT
    a.id, a.titulo, a.mensagem, a.nivel, a.expira_em, a.criado_por,
    a.criado_em, a.atualizado_em,
    u.nome AS criador_nome, u.cor AS criador_cor
FROM avisos a
JOIN usuarios u ON u.id = a.criado_por
WHERE a.setor_id = $1 AND (a.expira_em IS NULL OR a.expira_em > now())
ORDER BY
    CASE a.nivel WHEN 'critico' THEN 1 WHEN 'atencao' THEN 2 ELSE 3 END,
    a.criado_em DESC
LIMIT 50
`

type ListarAvisosAtivosRow struct {
	ID           pgtype.UUID        `json:"id"`
	Titulo       string             `json:"titulo"`
	Mensagem     string             `json:"mensagem"`
	Nivel        string             `json:"nivel"`
	ExpiraEm     pgtype.Timestamptz `json:"expira_em"`
	CriadoPor    pgtype.UUID        `json:"criado_por"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
	CriadorNome  string             `json:"criador_nome"`
	CriadorCor   string             `json:"criador_cor"`
}

func (q *Queries) ListarAvisosAtivos(ctx context.Context, setorID pgtype.UUID) ([]ListarAvisosAtivosRow, error) {
	rows, err := q.db.Query(ctx, listarAvisosAtivos, setorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarAvisosAtivosRow
	for rows.Next() {
		var i ListarAvisosAtivosRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Mensagem,
			&i.Nivel,
			&i.ExpiraEm,
			&i.CriadoPor,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.CriadorNome,
			&i.CriadorCor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterAviso = `-- name: ObterAviso :one
SELECT id, titulo, mensagem, nivel, expira_em, criado_por, criado_em, atualizado_em, setor_id FROM avisos WHERE id = $1 AND setor_id = $2
`

type ObterAvisoParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) ObterAviso(ctx context.Context, arg ObterAvisoParams) (Avisos, error) {
	row := q.db.QueryRow(ctx, obterAviso, arg.ID, arg.SetorID)
	var i Avisos
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Mensagem,
		&i.Nivel,
		&i.ExpiraEm,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}
