// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: estoque.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarItemEstoque = `-- name: AtualizarItemEstoque :one
UPDATE itens_estoque
SET nome = $2, unidade = $3, categoria = $4, estoque_minimo = $5, ativo = $6
WHERE id = $1
RETURNING id, nome, unidade, categoria, estoque_minimo, saldo, ativo, criado_em
`

type AtualizarItemEstoqueParams struct {
	ID            pgtype.UUID `json:"id"`
	Nome          string      `json:"nome"`
	Unidade       string      `json:"unidade"`
	Categoria     string      `json:"categoria"`
	EstoqueMinimo int32       `json:"estoque_minimo"`
	Ativo         bool        `json:"ativo"`
}

func (q *Queries) AtualizarItemEstoque(ctx context.Context, arg AtualizarItemEstoqueParams) (ItensEstoque, error) {
	row := q.db.QueryRow(ctx, atualizarItemEstoque,
		arg.ID,
		arg.Nome,
		arg.Unidade,
		arg.Categoria,
		arg.EstoqueMinimo,
		arg.Ativo,
	)
	var i ItensEstoque
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Unidade,
		&i.Categoria,
		&i.EstoqueMinimo,
		&i.Saldo,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const atualizarSaldoItemEstoque = `-- name: AtualizarSaldoItemEstoque :one
UPDATE itens_estoque
SET saldo = $2
WHERE id = $1
RETURNING id, nome, unidade, categoria, estoque_minimo, saldo, ativo, criado_em
`

type AtualizarSaldoItemEstoqueParams struct {
	ID    pgtype.UUID `json:"id"`
	Saldo int32       `json:"saldo"`
}

func (q *Queries) AtualizarSaldoItemEstoque(ctx context.Context, arg AtualizarSaldoItemEstoqueParams) (ItensEstoque, error) {
	row := q.db.QueryRow(ctx, atualizarSaldoItemEstoque, arg.ID, arg.Saldo)
	var i ItensEstoque
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Unidade,
		&i.Categoria,
		&i.EstoqueMinimo,
		&i.Saldo,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const bloquearItemEstoqueParaAtualizacao = `-- name: BloquearItemEstoqueParaAtualizacao :one
SELECT id, nome, unidade, categoria, estoque_minimo, saldo, ativo, criado_em
FROM itens_estoque
WHERE id = $1
FOR UPDATE
`

func (q *Queries) BloquearItemEstoqueParaAtualizacao(ctx context.Context, id pgtype.UUID) (ItensEstoque, error) {
	row := q.db.QueryRow(ctx, bloquearItemEstoqueParaAtualizacao, id)
	var i ItensEstoque
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Unidade,
		&i.Categoria,
		&i.EstoqueMinimo,
		&i.Saldo,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const buscarItemEstoquePorID = `-- name: BuscarItemEstoquePorID :one
SELECT id, nome, unidade, categoria, estoque_minimo, saldo, ativo, criado_em
FROM itens_estoque
WHERE id = $1
`

func (q *Queries) BuscarItemEstoquePorID(ctx context.Context, id pgtype.UUID) (ItensEstoque, error) {
	row := q.db.QueryRow(ctx, buscarItemEstoquePorID, id)
	var i ItensEstoque
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Unidade,
		&i.Categoria,
		&i.EstoqueMinimo,
		&i.Saldo,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const criarItemEstoque = `-- name: CriarItemEstoque :one
INSERT INTO itens_estoque (nome, unidade, categoria, estoque_minimo, saldo, ativo)
VALUES ($1, $2, $3, $4, 0, true)
RETURNING id, nome, unidade, categoria, estoque_minimo, saldo, ativo, criado_em
`

type CriarItemEstoqueParams struct {
	Nome          string `json:"nome"`
	Unidade       string `json:"unidade"`
	Categoria     string `json:"categoria"`
	EstoqueMinimo int32  `json:"estoque_minimo"`
}

func (q *Queries) CriarItemEstoque(ctx context.Context, arg CriarItemEstoqueParams) (ItensEstoque, error) {
	row := q.db.QueryRow(ctx, criarItemEstoque,
		arg.Nome,
		arg.Unidade,
		arg.Categoria,
		arg.EstoqueMinimo,
	)
	var i ItensEstoque
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Unidade,
		&i.Categoria,
		&i.EstoqueMinimo,
		&i.Saldo,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const criarMovimentacaoEstoque = `-- name: CriarMovimentacaoEstoque :one
INSERT INTO movimentacoes_estoque (item_id, tipo, quantidade, saldo_resultante, motivo, usuario_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, item_id, tipo, quantidade, saldo_resultante, motivo, usuario_id, criado_em
`

type CriarMovimentacaoEstoqueParams struct {
	ItemID          pgtype.UUID `json:"item_id"`
	Tipo            string      `json:"tipo"`
	Quantidade      int32       `json:"quantidade"`
	SaldoResultante int32       `json:"saldo_resultante"`
	Motivo          string      `json:"motivo"`
	UsuarioID       pgtype.UUID `json:"usuario_id"`
}

func (q *Queries) CriarMovimentacaoEstoque(ctx context.Context, arg CriarMovimentacaoEstoqueParams) (MovimentacoesEstoque, error) {
	row := q.db.QueryRow(ctx, criarMovimentacaoEstoque,
		arg.ItemID,
		arg.Tipo,
		arg.Quantidade,
		arg.SaldoResultante,
		arg.Motivo,
		arg.UsuarioID,
	)
	var i MovimentacoesEstoque
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Tipo,
		&i.Quantidade,
		&i.SaldoResultante,
		&i.Motivo,
		&i.UsuarioID,
		&i.CriadoEm,
	)
	return i, err
}

const listarCategoriasEstoque = `-- name: ListarCategoriasEstoque :many
SELECT DISTINCT categoria
FROM itens_estoque
WHERE ativo = true
ORDER BY categoria ASC
`

func (q *Queries) ListarCategoriasEstoque(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listarCategoriasEstoque)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var categoria string
		if err := rows.Scan(&categoria); err != nil {
			return nil, err
		}
		items = append(items, categoria)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarItensAbaixoDoMinimo = `-- name: ListarItensAbaixoDoMinimo :many
SELECT id, nome, unidade, categoria, estoque_minimo, saldo, ativo, criado_em
FROM itens_estoque
WHERE ativo = true AND saldo < estoque_minimo
ORDER BY (estoque_minimo - saldo) DESC, nome ASC
`

func (q *Queries) ListarItensAbaixoDoMinimo(ctx context.Context) ([]ItensEstoque, error) {
	rows, err := q.db.Query(ctx, listarItensAbaixoDoMinimo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItensEstoque
	for rows.Next() {
		var i ItensEstoque
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Unidade,
			&i.Categoria,
			&i.EstoqueMinimo,
			&i.Saldo,
			&i.Ativo,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarItensEstoque = `-- name: ListarItensEstoque :many
SELECT 
    id, nome, unidade, categoria, estoque_minimo, saldo, ativo, criado_em,
    (saldo < estoque_minimo)::boolean AS abaixo_do_minimo
FROM itens_estoque
WHERE 
    ($1::text IS NULL OR 
     unaccent(lower(nome)) ILIKE '%' || unaccent(lower($1)) || '%' OR
     unaccent(lower(categoria)) ILIKE '%' || unaccent(lower($1)) || '%')
    AND ($2::text IS NULL OR categoria = $2)
    AND ($3::boolean IS NULL OR ativo = $3)
ORDER BY nome ASC
`

type ListarItensEstoqueParams struct {
	Busca     pgtype.Text `json:"busca"`
	Categoria pgtype.Text `json:"categoria"`
	Ativo     pgtype.Bool `json:"ativo"`
}

type ListarItensEstoqueRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nome           string             `json:"nome"`
	Unidade        string             `json:"unidade"`
	Categoria      string             `json:"categoria"`
	EstoqueMinimo  int32              `json:"estoque_minimo"`
	Saldo          int32              `json:"saldo"`
	Ativo          bool               `json:"ativo"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AbaixoDoMinimo bool               `json:"abaixo_do_minimo"`
}

func (q *Queries) ListarItensEstoque(ctx context.Context, arg ListarItensEstoqueParams) ([]ListarItensEstoqueRow, error) {
	rows, err := q.db.Query(ctx, listarItensEstoque, arg.Busca, arg.Categoria, arg.Ativo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarItensEstoqueRow
	for rows.Next() {
		var i ListarItensEstoqueRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Unidade,
			&i.Categoria,
			&i.EstoqueMinimo,
			&i.Saldo,
			&i.Ativo,
			&i.CriadoEm,
			&i.AbaixoDoMinimo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMovimentacoesEstoque = `-- name: ListarMovimentacoesEstoque :many
SELECT 
    m.id, m.item_id, m.tipo, m.quantidade, m.saldo_resultante, m.motivo, m.usuario_id, m.criado_em,
    i.nome AS item_nome, i.unidade AS item_unidade,
    u.nome AS usuario_nome
FROM movimentacoes_estoque m
JOIN itens_estoque i ON i.id = m.item_id
JOIN usuarios u ON u.id = m.usuario_id
WHERE 
    ($3::uuid IS NULL OR m.item_id = $3)
    AND ($4::uuid IS NULL OR m.usuario_id = $4)
    AND ($5::text IS NULL OR m.tipo = $5)
    AND ($6::timestamptz IS NULL OR m.criado_em >= $6)
    AND ($7::timestamptz IS NULL OR m.criado_em <= $7)
ORDER BY m.criado_em DESC
LIMIT $1 OFFSET $2
`

type ListarMovimentacoesEstoqueParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	ItemID     pgtype.UUID        `json:"item_id"`
	UsuarioID  pgtype.UUID        `json:"usuario_id"`
	Tipo       pgtype.Text        `json:"tipo"`
	DataInicio pgtype.Timestamptz `json:"data_inicio"`
	DataFim    pgtype.Timestamptz `json:"data_fim"`
}

type ListarMovimentacoesEstoqueRow struct {
	ID              pgtype.UUID        `json:"id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	Tipo            string             `json:"tipo"`
	Quantidade      int32              `json:"quantidade"`
	SaldoResultante int32              `json:"saldo_resultante"`
	Motivo          string             `json:"motivo"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	ItemNome        string             `json:"item_nome"`
	ItemUnidade     string             `json:"item_unidade"`
	UsuarioNome     string             `json:"usuario_nome"`
}

func (q *Queries) ListarMovimentacoesEstoque(ctx context.Context, arg ListarMovimentacoesEstoqueParams) ([]ListarMovimentacoesEstoqueRow, error) {
	rows, err := q.db.Query(ctx, listarMovimentacoesEstoque,
		arg.Limit,
		arg.Offset,
		arg.ItemID,
		arg.UsuarioID,
		arg.Tipo,
		arg.DataInicio,
		arg.DataFim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarMovimentacoesEstoqueRow
	for rows.Next() {
		var i ListarMovimentacoesEstoqueRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Tipo,
			&i.Quantidade,
			&i.SaldoResultante,
			&i.Motivo,
			&i.UsuarioID,
			&i.CriadoEm,
			&i.ItemNome,
			&i.ItemUnidade,
			&i.UsuarioNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterUltimaMovimentacaoItem = `-- name: ObterUltimaMovimentacaoItem :one
SELECT m.id, m.item_id, m.tipo, m.quantidade, m.saldo_resultante, m.motivo, m.usuario_id, m.criado_em
FROM movimentacoes_estoque m
WHERE m.item_id = $1
ORDER BY m.criado_em DESC
LIMIT 1
`

func (q *Queries) ObterUltimaMovimentacaoItem(ctx context.Context, itemID pgtype.UUID) (MovimentacoesEstoque, error) {
	row := q.db.QueryRow(ctx, obterUltimaMovimentacaoItem, itemID)
	var i MovimentacoesEstoque
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Tipo,
		&i.Quantidade,
		&i.SaldoResultante,
		&i.Motivo,
		&i.UsuarioID,
		&i.CriadoEm,
	)
	return i, err
}
