// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: eventos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adicionarParticipanteEvento = `-- name: AdicionarParticipanteEvento :exec
INSERT INTO evento_participantes (evento_id, usuario_id)
SELECT e.id, u.id
FROM eventos e
JOIN usuarios u ON u.id = $1
WHERE e.id = $2 AND (u.setor_id = e.setor_id OR u.id = e.criado_por)
ON CONFLICT DO NOTHING
`

type AdicionarParticipanteEventoParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	EventoID  pgtype.UUID `json:"evento_id"`
}

// Só entra quem é do setor do evento (ou quem o criou)
func (q *Queries) AdicionarParticipanteEvento(ctx context.Context, arg AdicionarParticipanteEventoParams) error {
	_, err := q.db.Exec(ctx, adicionarParticipanteEvento, arg.UsuarioID, arg.EventoID)
	return err
}

const atualizarEvento = `-- name: AtualizarEvento :one
UPDATE eventos
SET titulo = $2, descricao = $3, inicio = $4, fim = $5, dia_inteiro = $6, recorrencia = $7, recorrencia_fim = $8, atualizado_em = now()
WHERE id = $1
RETURNING id, titulo, descricao, inicio, fim, dia_inteiro, criado_por, criado_em, atualizado_em, recorrencia, recorrencia_fim, setor_id
`

type AtualizarEventoParams struct {
	ID             pgtype.UUID        `json:"id"`
	Titulo         string             `json:"titulo"`
	Descricao      string             `json:"descricao"`
	Inicio         pgtype.Timestamptz `json:"inicio"`
	Fim            pgtype.Timestamptz `json:"fim"`
	DiaInteiro     bool               `json:"dia_inteiro"`
	Recorrencia    string             `json:"recorrencia"`
	RecorrenciaFim pgtype.Timestamptz `json:"recorrencia_fim"`
}

func (q *Queries) AtualizarEvento(ctx context.Context, arg AtualizarEventoParams) (Eventos, error) {
	row := q.db.QueryRow(ctx, atualizarEvento,
		arg.ID,
		arg.Titulo,
		arg.Descricao,
		arg.Inicio,
		arg.Fim,
		arg.DiaInteiro,
		arg.Recorrencia,
		arg.RecorrenciaFim,
	)
	var i Eventos
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.Inicio,
		&i.Fim,
		&i.DiaInteiro,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Recorrencia,
		&i.RecorrenciaFim,
		&i.SetorID,
	)
	return i, err
}

const buscarEventoPorID = `-- name: BuscarEventoPorID :one
SELECT e.id, e.titulo, e.descricao, e.inicio, e.fim, e.dia_inteiro, e.criado_por, e.criado_em, e.atualizado_em, e.recorrencia, e.recorrencia_fim
FROM eventos e
WHERE e.id = $1 AND e.setor_id = $2
`

type BuscarEventoPorIDParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

type BuscarEventoPorIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Titulo         string             `json:"titulo"`
	Descricao      string             `json:"descricao"`
	Inicio         pgtype.Timestamptz `json:"inicio"`
	Fim            pgtype.Timestamptz `json:"fim"`
	DiaInteiro     bool               `json:"dia_inteiro"`
	CriadoPor      pgtype.UUID        `json:"criado_por"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamptz `json:"atualizado_em"`
	Recorrencia    string             `json:"recorrencia"`
	RecorrenciaFim pgtype.Timestamptz `json:"recorrencia_fim"`
}

func (q *Queries) BuscarEventoPorID(ctx context.Context, arg BuscarEventoPorIDParams) (BuscarEventoPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarEventoPorID, arg.ID, arg.SetorID)
	var i BuscarEventoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.Inicio,
		&i.Fim,
		&i.DiaInteiro,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Recorrencia,
		&i.RecorrenciaFim,
	)
	return i, err
}

const criarEvento = `-- name: CriarEvento :one
INSERT INTO eventos (titulo, descricao, inicio, fim, dia_inteiro, criado_por, recorrencia, recorrencia_fim, setor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, titulo, descricao, inicio, fim, dia_inteiro, criado_por, criado_em, atualizado_em, recorrencia, recorrencia_fim, setor_id
`

type CriarEventoParams struct {
	Titulo         string             `json:"titulo"`
	Descricao      string             `json:"descricao"`
	Inicio         pgtype.Timestamptz `json:"inicio"`
	Fim            pgtype.Timestamptz `json:"fim"`
	DiaInteiro     bool               `json:"dia_inteiro"`
	CriadoPor      pgtype.UUID        `json:"criado_por"`
	Recorrencia    string             `json:"recorrencia"`
	RecorrenciaFim pgtype.Timestamptz `json:"recorrencia_fim"`
	SetorID        pgtype.UUID        `json:"setor_id"`
}

func (q *Queries) CriarEvento(ctx context.Context, arg CriarEventoParams) (Eventos, error) {
	row := q.db.QueryRow(ctx, criarEvento,
		arg.Titulo,
		arg.Descricao,
		arg.Inicio,
		arg.Fim,
		arg.DiaInteiro,
		arg.CriadoPor,
		arg.Recorrencia,
		arg.RecorrenciaFim,
		arg.SetorID,
	)
	var i Eventos
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.Inicio,
		&i.Fim,
		&i.DiaInteiro,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Recorrencia,
		&i.RecorrenciaFim,
		&i.SetorID,
	)
	return i, err
}

const deletarEvento = `-- name: DeletarEvento :exec
DELETE FROM eventos
WHERE id = $1
`

func (q *Queries) DeletarEvento(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarEvento, id)
	return err
}

const listarEventosIntervalo = `-- name: ListarEventosIntervalo :many
SELECT 
    e.id, e.titulo, e.descricao, e.inicio, e.fim, e.dia_inteiro, e.criado_por, e.criado_em, e.atualizado_em,
    e.recorrencia, e.recorrencia_fim,
    u.nome AS criador_nome, u.cor AS criador_cor
FROM eventos e
JOIN usuarios u ON u.id = e.criado_por
WHERE e.setor_id = $3
  AND ((e.fim >= $1 AND e.inicio <= $2)
   OR (e.recorrencia != 'nenhuma' AND e.inicio <= $2 AND (e.recorrencia_fim IS NULL OR e.recorrencia_fim >= $1)))
ORDER BY e.inicio ASC
`

type ListarEventosIntervaloParams struct {
	Fim     pgtype.Timestamptz `json:"fim"`
	Inicio  pgtype.Timestamptz `json:"inicio"`
	SetorID pgtype.UUID        `json:"setor_id"`
}

type ListarEventosIntervaloRow struct {
	ID             pgtype.UUID        `json:"id"`
	Titulo         string             `json:"titulo"`
	Descricao      string             `json:"descricao"`
	Inicio         pgtype.Timestamptz `json:"inicio"`
	Fim            pgtype.Timestamptz `json:"fim"`
	DiaInteiro     bool               `json:"dia_inteiro"`
	CriadoPor      pgtype.UUID        `json:"criado_por"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamptz `json:"atualizado_em"`
	Recorrencia    string             `json:"recorrencia"`
	RecorrenciaFim pgtype.Timestamptz `json:"recorrencia_fim"`
	CriadorNome    string             `json:"criador_nome"`
	CriadorCor     string             `json:"criador_cor"`
}

func (q *Queries) ListarEventosIntervalo(ctx context.Context, arg ListarEventosIntervaloParams) ([]ListarEventosIntervaloRow, error) {
	rows, err := q.db.Query(ctx, listarEventosIntervalo, arg.Fim, arg.Inicio, arg.SetorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEventosIntervaloRow
	for rows.Next() {
		var i ListarEventosIntervaloRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.Inicio,
			&i.Fim,
			&i.DiaInteiro,
			&i.CriadoPor,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.Recorrencia,
			&i.RecorrenciaFim,
			&i.CriadorNome,
			&i.CriadorCor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarParticipantesPorEvento = `-- name: ListarParticipantesPorEvento :many
SELECT ep.evento_id, ep.usuario_id, u.nome, u.cor
FROM evento_participantes ep
JOIN usuarios u ON u.id = ep.usuario_id
WHERE ep.evento_id = $1
`

type ListarParticipantesPorEventoRow struct {
	EventoID  pgtype.UUID `json:"evento_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Nome      string      `json:"nome"`
	Cor       string      `json:"cor"`
}

func (q *Queries) ListarParticipantesPorEvento(ctx context.Context, eventoID pgtype.UUID) ([]ListarParticipantesPorEventoRow, error) {
	rows, err := q.db.Query(ctx, listarParticipantesPorEvento, eventoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarParticipantesPorEventoRow
	for rows.Next() {
		var i ListarParticipantesPorEventoRow
		if err := rows.Scan(
			&i.EventoID,
			&i.UsuarioID,
			&i.Nome,
			&i.Cor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarParticipantesPorEventos = `-- name: ListarParticipantesPorEventos :many
SELECT ep.evento_id, ep.usuario_id, u.nome, u.cor
FROM evento_participantes ep
JOIN usuarios u ON u.id = ep.usuario_id
WHERE ep.evento_id = ANY($1::uuid[])
`

type ListarParticipantesPorEventosRow struct {
	EventoID  pgtype.UUID `json:"evento_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Nome      string      `json:"nome"`
	Cor       string      `json:"cor"`
}

func (q *Queries) ListarParticipantesPorEventos(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListarParticipantesPorEventosRow, error) {
	rows, err := q.db.Query(ctx, listarParticipantesPorEventos, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarParticipantesPorEventosRow
	for rows.Next() {
		var i ListarParticipantesPorEventosRow
		if err := rows.Scan(
			&i.EventoID,
			&i.UsuarioID,
			&i.Nome,
			&i.Cor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerParticipantesEvento = `-- name: RemoverParticipantesEvento :exec
DELETE FROM evento_participantes
WHERE evento_id = $1
`

func (q *Queries) RemoverParticipantesEvento(ctx context.Context, eventoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removerParticipantesEvento, eventoID)
	return err
}
