// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarLink = `-- name: AtualizarLink :one
UPDATE links
SET titulo = $2, url = $3, descricao = $4, categoria = $5, atualizado_em = now()
WHERE id = $1
RETURNING id, titulo, url, descricao, categoria, criado_por, criado_em, atualizado_em, setor_id
`

type AtualizarLinkParams struct {
	ID        pgtype.UUID `json:"id"`
	Titulo    string      `json:"titulo"`
	Url       string      `json:"url"`
	Descricao string      `json:"descricao"`
	Categoria string      `json:"categoria"`
}

func (q *Queries) AtualizarLink(ctx context.Context, arg AtualizarLinkParams) (Links, error) {
	row := q.db.QueryRow(ctx, atualizarLink,
		arg.ID,
		arg.Titulo,
		arg.Url,
		arg.Descricao,
		arg.Categoria,
	)
	var i Links
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Url,
		&i.Descricao,
		&i.Categoria,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const criarLink = `-- name: CriarLink :one
INSERT INTO links (titulo, url, descricao, categoria, criado_por, setor_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, titulo, url, descricao, categoria, criado_por, criado_em, atualizado_em, setor_id
`

type CriarLinkParams struct {
	Titulo    string      `json:"titulo"`
	Url       string      `json:"url"`
	Descricao string      `json:"descricao"`
	Categoria string      `json:"categoria"`
	CriadoPor pgtype.UUID `json:"criado_por"`
	SetorID   pgtype.UUID `json:"setor_id"`
}

func (q *Queries) CriarLink(ctx context.Context, arg CriarLinkParams) (Links, error) {
	row := q.db.QueryRow(ctx, criarLink,
		arg.Titulo,
		arg.Url,
		arg.Descricao,
		arg.Categoria,
		arg.CriadoPor,
		arg.SetorID,
	)
	var i Links
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Url,
		&i.Descricao,
		&i.Categoria,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const deletarLink = `-- name: DeletarLink :exec
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeletarLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarLink, id)
	return err
}

const listarLinks = `-- name: ListarLinks :many
SELECT
    l.id, l.titulo, l.url, l.descricao, l.categoria, l.criado_por, l.criado_em,
    u.nome AS criador_nome
FROM links l
JOIN usuarios u ON u.id = l.criado_por
WHERE l.setor_id = $1
ORDER BY lower(l.categoria), lower(l.titulo)
`

type ListarLinksRow struct {
	ID          pgtype.UUID        `json:"id"`
	Titulo      string             `json:"titulo"`
	Url         string             `json:"url"`
	Descricao   string             `json:"descricao"`
	Categoria   string             `json:"categoria"`
	CriadoPor   pgtype.UUID        `json:"criado_por"`
	CriadoEm    pgtype.Timestamptz `json:"criado_em"`
	CriadorNome string             `json:"criador_nome"`
}

func (q *Queries) ListarLinks(ctx context.Context, setorID pgtype.UUID) ([]ListarLinksRow, error) {
	rows, err := q.db.Query(ctx, listarLinks, setorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarLinksRow
	for rows.Next() {
		var i ListarLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Url,
			&i.Descricao,
			&i.Categoria,
			&i.CriadoPor,
			&i.CriadoEm,
			&i.CriadorNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterLink = `-- name: ObterLink :one
SELECT id, titulo, url, descricao, categoria, criado_por, criado_em, atualizado_em, setor_id FROM links WHERE id = $1 AND setor_id = $2
`

type ObterLinkParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) ObterLink(ctx context.Context, arg ObterLinkParams) (Links, error) {
	row := q.db.QueryRow(ctx, obterLink, arg.ID, arg.SetorID)
	var i Links
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Url,
		&i.Descricao,
		&i.Categoria,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}
