// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Atendimentos struct {
	ID              pgtype.UUID        `json:"id"`
	ClienteNome     string             `json:"cliente_nome"`
	Descricao       string             `json:"descricao"`
	DataAtendimento pgtype.Timestamptz `json:"data_atendimento"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

type EventoParticipantes struct {
	EventoID  pgtype.UUID `json:"evento_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type Eventos struct {
	ID             pgtype.UUID        `json:"id"`
	Titulo         string             `json:"titulo"`
	Descricao      string             `json:"descricao"`
	Inicio         pgtype.Timestamptz `json:"inicio"`
	Fim            pgtype.Timestamptz `json:"fim"`
	DiaInteiro     bool               `json:"dia_inteiro"`
	CriadoPor      pgtype.UUID        `json:"criado_por"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamptz `json:"atualizado_em"`
	Recorrencia    string             `json:"recorrencia"`
	RecorrenciaFim pgtype.Timestamptz `json:"recorrencia_fim"`
}

type ItensEstoque struct {
	ID            pgtype.UUID        `json:"id"`
	Nome          string             `json:"nome"`
	Unidade       string             `json:"unidade"`
	Categoria     string             `json:"categoria"`
	EstoqueMinimo int32              `json:"estoque_minimo"`
	Saldo         int32              `json:"saldo"`
	Ativo         bool               `json:"ativo"`
	CriadoEm      pgtype.Timestamptz `json:"criado_em"`
}

type MovimentacoesEstoque struct {
	ID              pgtype.UUID        `json:"id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	Tipo            string             `json:"tipo"`
	Quantidade      int32              `json:"quantidade"`
	SaldoResultante int32              `json:"saldo_resultante"`
	Motivo          string             `json:"motivo"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
}

type Sessoes struct {
	ID          pgtype.UUID        `json:"id"`
	TokenHash   string             `json:"token_hash"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	ExpiraEm    pgtype.Timestamptz `json:"expira_em"`
	UltimoUsoEm pgtype.Timestamptz `json:"ultimo_uso_em"`
	CriadoEm    pgtype.Timestamptz `json:"criado_em"`
}

type TarefaComentarios struct {
	ID        pgtype.UUID        `json:"id"`
	TarefaID  pgtype.UUID        `json:"tarefa_id"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	Conteudo  string             `json:"conteudo"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Tarefas struct {
	ID            pgtype.UUID        `json:"id"`
	Titulo        string             `json:"titulo"`
	Descricao     string             `json:"descricao"`
	Status        string             `json:"status"`
	Prioridade    string             `json:"prioridade"`
	Prazo         pgtype.Timestamptz `json:"prazo"`
	CriadoPor     pgtype.UUID        `json:"criado_por"`
	ResponsavelID pgtype.UUID        `json:"responsavel_id"`
	ConcluidaEm   pgtype.Timestamptz `json:"concluida_em"`
	CriadoEm      pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm  pgtype.Timestamptz `json:"atualizado_em"`
}

type UsuarioFotos struct {
	UsuarioID    pgtype.UUID        `json:"usuario_id"`
	Conteudo     []byte             `json:"conteudo"`
	Mime         string             `json:"mime"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type Usuarios struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	PinHash          string             `json:"pin_hash"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}
