// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssistenteUso struct {
	Dia       pgtype.Date `json:"dia"`
	Neurons   float64     `json:"neurons"`
	Perguntas int32       `json:"perguntas"`
}

type Atendimentos struct {
	ID              pgtype.UUID        `json:"id"`
	ClienteNome     string             `json:"cliente_nome"`
	Descricao       string             `json:"descricao"`
	DataAtendimento pgtype.Timestamptz `json:"data_atendimento"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

type Avisos struct {
	ID           pgtype.UUID        `json:"id"`
	Titulo       string             `json:"titulo"`
	Mensagem     string             `json:"mensagem"`
	Nivel        string             `json:"nivel"`
	ExpiraEm     pgtype.Timestamptz `json:"expira_em"`
	CriadoPor    pgtype.UUID        `json:"criado_por"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type EventoParticipantes struct {
	EventoID  pgtype.UUID `json:"evento_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
}

type Eventos struct {
	ID             pgtype.UUID        `json:"id"`
	Titulo         string             `json:"titulo"`
	Descricao      string             `json:"descricao"`
	Inicio         pgtype.Timestamptz `json:"inicio"`
	Fim            pgtype.Timestamptz `json:"fim"`
	DiaInteiro     bool               `json:"dia_inteiro"`
	CriadoPor      pgtype.UUID        `json:"criado_por"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamptz `json:"atualizado_em"`
	Recorrencia    string             `json:"recorrencia"`
	RecorrenciaFim pgtype.Timestamptz `json:"recorrencia_fim"`
}

type ItensEstoque struct {
	ID            pgtype.UUID        `json:"id"`
	Nome          string             `json:"nome"`
	Unidade       string             `json:"unidade"`
	Categoria     string             `json:"categoria"`
	EstoqueMinimo int32              `json:"estoque_minimo"`
	Saldo         int32              `json:"saldo"`
	Ativo         bool               `json:"ativo"`
	CriadoEm      pgtype.Timestamptz `json:"criado_em"`
}

type Links struct {
	ID           pgtype.UUID        `json:"id"`
	Titulo       string             `json:"titulo"`
	Url          string             `json:"url"`
	Descricao    string             `json:"descricao"`
	Categoria    string             `json:"categoria"`
	CriadoPor    pgtype.UUID        `json:"criado_por"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type MonitorQuedas struct {
	ID        pgtype.UUID        `json:"id"`
	MonitorID pgtype.UUID        `json:"monitor_id"`
	Inicio    pgtype.Timestamptz `json:"inicio"`
	Fim       pgtype.Timestamptz `json:"fim"`
	Erro      string             `json:"erro"`
	TicketID  pgtype.UUID        `json:"ticket_id"`
}

type Monitores struct {
	ID             pgtype.UUID        `json:"id"`
	Nome           string             `json:"nome"`
	Tipo           string             `json:"tipo"`
	Alvo           string             `json:"alvo"`
	IntervaloSeg   int32              `json:"intervalo_seg"`
	AbrirTicket    bool               `json:"abrir_ticket"`
	Ativo          bool               `json:"ativo"`
	Status         string             `json:"status"`
	FalhasSeguidas int32              `json:"falhas_seguidas"`
	LatenciaMs     pgtype.Int4        `json:"latencia_ms"`
	UltimoErro     string             `json:"ultimo_erro"`
	VerificadoEm   pgtype.Timestamptz `json:"verificado_em"`
	StatusDesde    pgtype.Timestamptz `json:"status_desde"`
	CriadoPor      pgtype.UUID        `json:"criado_por"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamptz `json:"atualizado_em"`
}

type MovimentacoesEstoque struct {
	ID              pgtype.UUID        `json:"id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	Tipo            string             `json:"tipo"`
	Quantidade      int32              `json:"quantidade"`
	SaldoResultante int32              `json:"saldo_resultante"`
	Motivo          string             `json:"motivo"`
	UsuarioID       pgtype.UUID        `json:"usuario_id"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
}

type Plantoes struct {
	ID           pgtype.UUID        `json:"id"`
	UsuarioID    pgtype.UUID        `json:"usuario_id"`
	Tipo         string             `json:"tipo"`
	Inicio       pgtype.Date        `json:"inicio"`
	Fim          pgtype.Date        `json:"fim"`
	Observacao   string             `json:"observacao"`
	CriadoPor    pgtype.UUID        `json:"criado_por"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type ProcedimentoRevisoes struct {
	ID             pgtype.UUID        `json:"id"`
	ProcedimentoID pgtype.UUID        `json:"procedimento_id"`
	Titulo         string             `json:"titulo"`
	Categoria      string             `json:"categoria"`
	Corpo          string             `json:"corpo"`
	Ativo          bool               `json:"ativo"`
	Nota           string             `json:"nota"`
	EditadoPor     pgtype.UUID        `json:"editado_por"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
}

type Procedimentos struct {
	ID            pgtype.UUID        `json:"id"`
	Titulo        string             `json:"titulo"`
	Categoria     string             `json:"categoria"`
	Corpo         string             `json:"corpo"`
	Ativo         bool               `json:"ativo"`
	CriadoPor     pgtype.UUID        `json:"criado_por"`
	AtualizadoPor pgtype.UUID        `json:"atualizado_por"`
	CriadoEm      pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm  pgtype.Timestamptz `json:"atualizado_em"`
}

type Sessoes struct {
	ID          pgtype.UUID        `json:"id"`
	TokenHash   string             `json:"token_hash"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	ExpiraEm    pgtype.Timestamptz `json:"expira_em"`
	UltimoUsoEm pgtype.Timestamptz `json:"ultimo_uso_em"`
	CriadoEm    pgtype.Timestamptz `json:"criado_em"`
}

type TarefaComentarios struct {
	ID        pgtype.UUID        `json:"id"`
	TarefaID  pgtype.UUID        `json:"tarefa_id"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	Conteudo  string             `json:"conteudo"`
	CriadoEm  pgtype.Timestamptz `json:"criado_em"`
}

type Tarefas struct {
	ID            pgtype.UUID        `json:"id"`
	Titulo        string             `json:"titulo"`
	Descricao     string             `json:"descricao"`
	Status        string             `json:"status"`
	Prioridade    string             `json:"prioridade"`
	Prazo         pgtype.Timestamptz `json:"prazo"`
	CriadoPor     pgtype.UUID        `json:"criado_por"`
	ResponsavelID pgtype.UUID        `json:"responsavel_id"`
	ConcluidaEm   pgtype.Timestamptz `json:"concluida_em"`
	CriadoEm      pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm  pgtype.Timestamptz `json:"atualizado_em"`
}

type TecnicoRegistros struct {
	ID                   pgtype.UUID        `json:"id"`
	TecnicoID            pgtype.UUID        `json:"tecnico_id"`
	Entrada              pgtype.Timestamptz `json:"entrada"`
	Saida                pgtype.Timestamptz `json:"saida"`
	Observacao           string             `json:"observacao"`
	EntradaRegistradaPor pgtype.UUID        `json:"entrada_registrada_por"`
	SaidaRegistradaPor   pgtype.UUID        `json:"saida_registrada_por"`
	CriadoEm             pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm         pgtype.Timestamptz `json:"atualizado_em"`
	Atividades           string             `json:"atividades"`
}

type Tecnicos struct {
	ID       pgtype.UUID        `json:"id"`
	Nome     string             `json:"nome"`
	Empresa  string             `json:"empresa"`
	Ativo    bool               `json:"ativo"`
	CriadoEm pgtype.Timestamptz `json:"criado_em"`
}

type Tickets struct {
	ID              pgtype.UUID        `json:"id"`
	Numero          int64              `json:"numero"`
	SolicitanteNome string             `json:"solicitante_nome"`
	Titulo          string             `json:"titulo"`
	Descricao       string             `json:"descricao"`
	Prioridade      string             `json:"prioridade"`
	Status          string             `json:"status"`
	TarefaID        pgtype.UUID        `json:"tarefa_id"`
	TratadoPor      pgtype.UUID        `json:"tratado_por"`
	TratadoEm       pgtype.Timestamptz `json:"tratado_em"`
	OrigemIp        string             `json:"origem_ip"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
}

type UsuarioFotos struct {
	UsuarioID    pgtype.UUID        `json:"usuario_id"`
	Conteudo     []byte             `json:"conteudo"`
	Mime         string             `json:"mime"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

type Usuarios struct {
	ID                pgtype.UUID        `json:"id"`
	Nome              string             `json:"nome"`
	Cor               string             `json:"cor"`
	PinHash           string             `json:"pin_hash"`
	Papel             string             `json:"papel"`
	Ativo             bool               `json:"ativo"`
	TentativasFalhas  int32              `json:"tentativas_falhas"`
	BloqueadoAte      pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm          pgtype.Timestamptz `json:"criado_em"`
	Tema              string             `json:"tema"`
	DeveTrocarPin     bool               `json:"deve_trocar_pin"`
	UltimaTentativaEm pgtype.Timestamptz `json:"ultima_tentativa_em"`
	Bloqueios         int32              `json:"bloqueios"`
}
