// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitores.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abrirQueda = `-- name: AbrirQueda :one
INSERT INTO monitor_quedas (monitor_id, erro)
VALUES ($1, $2)
RETURNING id
`

type AbrirQuedaParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	Erro      string      `json:"erro"`
}

func (q *Queries) AbrirQueda(ctx context.Context, arg AbrirQuedaParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, abrirQueda, arg.MonitorID, arg.Erro)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const atualizarMonitor = `-- name: AtualizarMonitor :one
UPDATE monitores
SET nome = $2, tipo = $3, alvo = $4, intervalo_seg = $5, abrir_ticket = $6, ativo = $7,
    atualizado_em = now()
WHERE id = $1
RETURNING id, nome, tipo, alvo, intervalo_seg, abrir_ticket, ativo, status, falhas_seguidas, latencia_ms, ultimo_erro, verificado_em, status_desde, criado_por, criado_em, atualizado_em
`

type AtualizarMonitorParams struct {
	ID           pgtype.UUID `json:"id"`
	Nome         string      `json:"nome"`
	Tipo         string      `json:"tipo"`
	Alvo         string      `json:"alvo"`
	IntervaloSeg int32       `json:"intervalo_seg"`
	AbrirTicket  bool        `json:"abrir_ticket"`
	Ativo        bool        `json:"ativo"`
}

func (q *Queries) AtualizarMonitor(ctx context.Context, arg AtualizarMonitorParams) (Monitores, error) {
	row := q.db.QueryRow(ctx, atualizarMonitor,
		arg.ID,
		arg.Nome,
		arg.Tipo,
		arg.Alvo,
		arg.IntervaloSeg,
		arg.AbrirTicket,
		arg.Ativo,
	)
	var i Monitores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Tipo,
		&i.Alvo,
		&i.IntervaloSeg,
		&i.AbrirTicket,
		&i.Ativo,
		&i.Status,
		&i.FalhasSeguidas,
		&i.LatenciaMs,
		&i.UltimoErro,
		&i.VerificadoEm,
		&i.StatusDesde,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const bloquearMonitor = `-- name: BloquearMonitor :one
SELECT id, nome, tipo, alvo, intervalo_seg, abrir_ticket, ativo, status, falhas_seguidas, latencia_ms, ultimo_erro, verificado_em, status_desde, criado_por, criado_em, atualizado_em FROM monitores WHERE id = $1 FOR UPDATE
`

func (q *Queries) BloquearMonitor(ctx context.Context, id pgtype.UUID) (Monitores, error) {
	row := q.db.QueryRow(ctx, bloquearMonitor, id)
	var i Monitores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Tipo,
		&i.Alvo,
		&i.IntervaloSeg,
		&i.AbrirTicket,
		&i.Ativo,
		&i.Status,
		&i.FalhasSeguidas,
		&i.LatenciaMs,
		&i.UltimoErro,
		&i.VerificadoEm,
		&i.StatusDesde,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const criarMonitor = `-- name: CriarMonitor :one
INSERT INTO monitores (nome, tipo, alvo, intervalo_seg, abrir_ticket, criado_por)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, nome, tipo, alvo, intervalo_seg, abrir_ticket, ativo, status, falhas_seguidas, latencia_ms, ultimo_erro, verificado_em, status_desde, criado_por, criado_em, atualizado_em
`

type CriarMonitorParams struct {
	Nome         string      `json:"nome"`
	Tipo         string      `json:"tipo"`
	Alvo         string      `json:"alvo"`
	IntervaloSeg int32       `json:"intervalo_seg"`
	AbrirTicket  bool        `json:"abrir_ticket"`
	CriadoPor    pgtype.UUID `json:"criado_por"`
}

func (q *Queries) CriarMonitor(ctx context.Context, arg CriarMonitorParams) (Monitores, error) {
	row := q.db.QueryRow(ctx, criarMonitor,
		arg.Nome,
		arg.Tipo,
		arg.Alvo,
		arg.IntervaloSeg,
		arg.AbrirTicket,
		arg.CriadoPor,
	)
	var i Monitores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Tipo,
		&i.Alvo,
		&i.IntervaloSeg,
		&i.AbrirTicket,
		&i.Ativo,
		&i.Status,
		&i.FalhasSeguidas,
		&i.LatenciaMs,
		&i.UltimoErro,
		&i.VerificadoEm,
		&i.StatusDesde,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deletarMonitor = `-- name: DeletarMonitor :exec
DELETE FROM monitores WHERE id = $1
`

func (q *Queries) DeletarMonitor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarMonitor, id)
	return err
}

const fecharQuedaAberta = `-- name: FecharQuedaAberta :exec
UPDATE monitor_quedas SET fim = now() WHERE monitor_id = $1 AND fim IS NULL
`

func (q *Queries) FecharQuedaAberta(ctx context.Context, monitorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, fecharQuedaAberta, monitorID)
	return err
}

const listarMonitores = `-- name: ListarMonitores :many
SELECT id, nome, tipo, alvo, intervalo_seg, abrir_ticket, ativo, status, falhas_seguidas, latencia_ms, ultimo_erro, verificado_em, status_desde, criado_por, criado_em, atualizado_em FROM monitores
ORDER BY
    ativo DESC,
    CASE status WHEN 'offline' THEN 1 WHEN 'pendente' THEN 2 ELSE 3 END,
    lower(nome)
`

func (q *Queries) ListarMonitores(ctx context.Context) ([]Monitores, error) {
	rows, err := q.db.Query(ctx, listarMonitores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitores
	for rows.Next() {
		var i Monitores
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Tipo,
			&i.Alvo,
			&i.IntervaloSeg,
			&i.AbrirTicket,
			&i.Ativo,
			&i.Status,
			&i.FalhasSeguidas,
			&i.LatenciaMs,
			&i.UltimoErro,
			&i.VerificadoEm,
			&i.StatusDesde,
			&i.CriadoPor,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMonitoresOffline = `-- name: ListarMonitoresOffline :many
SELECT id, nome, tipo, alvo, ultimo_erro, status_desde FROM monitores
WHERE ativo AND status = 'offline'
ORDER BY status_desde
`

type ListarMonitoresOfflineRow struct {
	ID          pgtype.UUID        `json:"id"`
	Nome        string             `json:"nome"`
	Tipo        string             `json:"tipo"`
	Alvo        string             `json:"alvo"`
	UltimoErro  string             `json:"ultimo_erro"`
	StatusDesde pgtype.Timestamptz `json:"status_desde"`
}

func (q *Queries) ListarMonitoresOffline(ctx context.Context) ([]ListarMonitoresOfflineRow, error) {
	rows, err := q.db.Query(ctx, listarMonitoresOffline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarMonitoresOfflineRow
	for rows.Next() {
		var i ListarMonitoresOfflineRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Tipo,
			&i.Alvo,
			&i.UltimoErro,
			&i.StatusDesde,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMonitoresParaVerificar = `-- name: ListarMonitoresParaVerificar :many
SELECT id, nome, tipo, alvo, intervalo_seg, abrir_ticket, ativo, status, falhas_seguidas, latencia_ms, ultimo_erro, verificado_em, status_desde, criado_por, criado_em, atualizado_em FROM monitores
WHERE ativo
  AND (verificado_em IS NULL OR verificado_em <= now() - make_interval(secs => intervalo_seg))
`

func (q *Queries) ListarMonitoresParaVerificar(ctx context.Context) ([]Monitores, error) {
	rows, err := q.db.Query(ctx, listarMonitoresParaVerificar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitores
	for rows.Next() {
		var i Monitores
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Tipo,
			&i.Alvo,
			&i.IntervaloSeg,
			&i.AbrirTicket,
			&i.Ativo,
			&i.Status,
			&i.FalhasSeguidas,
			&i.LatenciaMs,
			&i.UltimoErro,
			&i.VerificadoEm,
			&i.StatusDesde,
			&i.CriadoPor,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarQuedasMonitor = `-- name: ListarQuedasMonitor :many
SELECT q.id, q.inicio, q.fim, q.erro, tk.numero AS ticket_numero
FROM monitor_quedas q
LEFT JOIN tickets tk ON tk.id = q.ticket_id
WHERE q.monitor_id = $1
ORDER BY q.inicio DESC
LIMIT 20
`

type ListarQuedasMonitorRow struct {
	ID           pgtype.UUID        `json:"id"`
	Inicio       pgtype.Timestamptz `json:"inicio"`
	Fim          pgtype.Timestamptz `json:"fim"`
	Erro         string             `json:"erro"`
	TicketNumero pgtype.Int8        `json:"ticket_numero"`
}

func (q *Queries) ListarQuedasMonitor(ctx context.Context, monitorID pgtype.UUID) ([]ListarQuedasMonitorRow, error) {
	rows, err := q.db.Query(ctx, listarQuedasMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarQuedasMonitorRow
	for rows.Next() {
		var i ListarQuedasMonitorRow
		if err := rows.Scan(
			&i.ID,
			&i.Inicio,
			&i.Fim,
			&i.Erro,
			&i.TicketNumero,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterMonitor = `-- name: ObterMonitor :one
SELECT id, nome, tipo, alvo, intervalo_seg, abrir_ticket, ativo, status, falhas_seguidas, latencia_ms, ultimo_erro, verificado_em, status_desde, criado_por, criado_em, atualizado_em FROM monitores WHERE id = $1
`

func (q *Queries) ObterMonitor(ctx context.Context, id pgtype.UUID) (Monitores, error) {
	row := q.db.QueryRow(ctx, obterMonitor, id)
	var i Monitores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Tipo,
		&i.Alvo,
		&i.IntervaloSeg,
		&i.AbrirTicket,
		&i.Ativo,
		&i.Status,
		&i.FalhasSeguidas,
		&i.LatenciaMs,
		&i.UltimoErro,
		&i.VerificadoEm,
		&i.StatusDesde,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const registrarVerificacao = `-- name: RegistrarVerificacao :exec
UPDATE monitores
SET status = $1::varchar,
    falhas_seguidas = $2,
    latencia_ms = $3,
    ultimo_erro = $4,
    verificado_em = now(),
    status_desde = CASE WHEN status = $1::varchar THEN status_desde ELSE now() END
WHERE id = $5
`

type RegistrarVerificacaoParams struct {
	Status         string      `json:"status"`
	FalhasSeguidas int32       `json:"falhas_seguidas"`
	LatenciaMs     pgtype.Int4 `json:"latencia_ms"`
	UltimoErro     string      `json:"ultimo_erro"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) RegistrarVerificacao(ctx context.Context, arg RegistrarVerificacaoParams) error {
	_, err := q.db.Exec(ctx, registrarVerificacao,
		arg.Status,
		arg.FalhasSeguidas,
		arg.LatenciaMs,
		arg.UltimoErro,
		arg.ID,
	)
	return err
}

const reiniciarEstadoMonitor = `-- name: ReiniciarEstadoMonitor :exec
UPDATE monitores
SET status = 'pendente', falhas_seguidas = 0, latencia_ms = NULL, ultimo_erro = '',
    verificado_em = NULL, status_desde = now()
WHERE id = $1
`

// Depois de trocar o alvo ou desligar: a próxima verificação decide de novo.
func (q *Queries) ReiniciarEstadoMonitor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reiniciarEstadoMonitor, id)
	return err
}

const resumoMonitores = `-- name: ResumoMonitores :one
SELECT
    count(*) FILTER (WHERE ativo) AS ativos,
    count(*) FILTER (WHERE ativo AND status = 'online') AS online,
    count(*) FILTER (WHERE ativo AND status = 'offline') AS offline
FROM monitores
`

type ResumoMonitoresRow struct {
	Ativos  int64 `json:"ativos"`
	Online  int64 `json:"online"`
	Offline int64 `json:"offline"`
}

func (q *Queries) ResumoMonitores(ctx context.Context) (ResumoMonitoresRow, error) {
	row := q.db.QueryRow(ctx, resumoMonitores)
	var i ResumoMonitoresRow
	err := row.Scan(&i.Ativos, &i.Online, &i.Offline)
	return i, err
}

const segundosForaUltimas24h = `-- name: SegundosForaUltimas24h :many
SELECT
    monitor_id,
    COALESCE(sum(EXTRACT(EPOCH FROM (
        COALESCE(fim, now()) - GREATEST(inicio, now() - interval '24 hours')
    ))), 0)::float8 AS segundos
FROM monitor_quedas
WHERE COALESCE(fim, now()) > now() - interval '24 hours'
GROUP BY monitor_id
`

type SegundosForaUltimas24hRow struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	Segundos  float64     `json:"segundos"`
}

// Tempo em queda de cada monitor dentro das últimas 24 horas
func (q *Queries) SegundosForaUltimas24h(ctx context.Context) ([]SegundosForaUltimas24hRow, error) {
	rows, err := q.db.Query(ctx, segundosForaUltimas24h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SegundosForaUltimas24hRow
	for rows.Next() {
		var i SegundosForaUltimas24hRow
		if err := rows.Scan(&i.MonitorID, &i.Segundos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vincularTicketQueda = `-- name: VincularTicketQueda :exec
UPDATE monitor_quedas SET ticket_id = $2 WHERE id = $1
`

type VincularTicketQuedaParams struct {
	ID       pgtype.UUID `json:"id"`
	TicketID pgtype.UUID `json:"ticket_id"`
}

func (q *Queries) VincularTicketQueda(ctx context.Context, arg VincularTicketQuedaParams) error {
	_, err := q.db.Exec(ctx, vincularTicketQueda, arg.ID, arg.TicketID)
	return err
}
