// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plantoes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarPlantao = `-- name: AtualizarPlantao :one
UPDATE plantoes
SET nome = $2, tipo = $3, inicio = $4, fim = $5, observacao = $6,
    folga_inicio = $7, folga_fim = $8, atualizado_em = now()
WHERE id = $1
RETURNING id, tipo, inicio, fim, observacao, criado_por, criado_em, atualizado_em, setor_id, nome, folga_inicio, folga_fim
`

type AtualizarPlantaoParams struct {
	ID          pgtype.UUID `json:"id"`
	Nome        string      `json:"nome"`
	Tipo        string      `json:"tipo"`
	Inicio      pgtype.Date `json:"inicio"`
	Fim         pgtype.Date `json:"fim"`
	Observacao  string      `json:"observacao"`
	FolgaInicio pgtype.Date `json:"folga_inicio"`
	FolgaFim    pgtype.Date `json:"folga_fim"`
}

func (q *Queries) AtualizarPlantao(ctx context.Context, arg AtualizarPlantaoParams) (Plantoes, error) {
	row := q.db.QueryRow(ctx, atualizarPlantao,
		arg.ID,
		arg.Nome,
		arg.Tipo,
		arg.Inicio,
		arg.Fim,
		arg.Observacao,
		arg.FolgaInicio,
		arg.FolgaFim,
	)
	var i Plantoes
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
		&i.Observacao,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
		&i.Nome,
		&i.FolgaInicio,
		&i.FolgaFim,
	)
	return i, err
}

const buscarConflitoFolga = `-- name: BuscarConflitoFolga :one
SELECT inicio, fim, folga_inicio, folga_fim, tipo
FROM plantoes
WHERE setor_id = $1
  AND lower(nome) = lower($2)
  AND ($3::uuid IS NULL OR id <> $3)
  AND (
    (folga_inicio IS NOT NULL AND folga_fim >= $4::date AND folga_inicio <= $5::date)
    OR ($6::date IS NOT NULL
        AND fim >= $6::date AND inicio <= $7::date)
  )
ORDER BY inicio
LIMIT 1
`

type BuscarConflitoFolgaParams struct {
	SetorID         pgtype.UUID `json:"setor_id"`
	Nome            string      `json:"nome"`
	IgnorarID       pgtype.UUID `json:"ignorar_id"`
	Inicio          pgtype.Date `json:"inicio"`
	Fim             pgtype.Date `json:"fim"`
	NovaFolgaInicio pgtype.Date `json:"nova_folga_inicio"`
	NovaFolgaFim    pgtype.Date `json:"nova_folga_fim"`
}

type BuscarConflitoFolgaRow struct {
	Inicio      pgtype.Date `json:"inicio"`
	Fim         pgtype.Date `json:"fim"`
	FolgaInicio pgtype.Date `json:"folga_inicio"`
	FolgaFim    pgtype.Date `json:"folga_fim"`
	Tipo        string      `json:"tipo"`
}

// Ninguém trabalha na própria folga: nem turno novo sobre uma folga já
// marcada, nem folga nova sobre um turno já marcado (de qualquer tipo)
func (q *Queries) BuscarConflitoFolga(ctx context.Context, arg BuscarConflitoFolgaParams) (BuscarConflitoFolgaRow, error) {
	row := q.db.QueryRow(ctx, buscarConflitoFolga,
		arg.SetorID,
		arg.Nome,
		arg.IgnorarID,
		arg.Inicio,
		arg.Fim,
		arg.NovaFolgaInicio,
		arg.NovaFolgaFim,
	)
	var i BuscarConflitoFolgaRow
	err := row.Scan(
		&i.Inicio,
		&i.Fim,
		&i.FolgaInicio,
		&i.FolgaFim,
		&i.Tipo,
	)
	return i, err
}

const buscarConflitoPlantao = `-- name: BuscarConflitoPlantao :one
SELECT inicio, fim, nome
FROM plantoes
WHERE setor_id = $1
  AND lower(nome) = lower($2)
  AND tipo = $3
  AND fim >= $4::date
  AND inicio <= $5::date
  AND ($6::uuid IS NULL OR id <> $6)
ORDER BY inicio
LIMIT 1
`

type BuscarConflitoPlantaoParams struct {
	SetorID   pgtype.UUID `json:"setor_id"`
	Nome      string      `json:"nome"`
	Tipo      string      `json:"tipo"`
	Inicio    pgtype.Date `json:"inicio"`
	Fim       pgtype.Date `json:"fim"`
	IgnorarID pgtype.UUID `json:"ignorar_id"`
}

type BuscarConflitoPlantaoRow struct {
	Inicio pgtype.Date `json:"inicio"`
	Fim    pgtype.Date `json:"fim"`
	Nome   string      `json:"nome"`
}

// A mesma pessoa (pelo nome, sem diferenciar maiúsculas) não pode ter dois
// turnos do mesmo tipo sobrepostos no setor
func (q *Queries) BuscarConflitoPlantao(ctx context.Context, arg BuscarConflitoPlantaoParams) (BuscarConflitoPlantaoRow, error) {
	row := q.db.QueryRow(ctx, buscarConflitoPlantao,
		arg.SetorID,
		arg.Nome,
		arg.Tipo,
		arg.Inicio,
		arg.Fim,
		arg.IgnorarID,
	)
	var i BuscarConflitoPlantaoRow
	err := row.Scan(&i.Inicio, &i.Fim, &i.Nome)
	return i, err
}

const criarPlantao = `-- name: CriarPlantao :one
INSERT INTO plantoes (nome, tipo, inicio, fim, observacao, folga_inicio, folga_fim, criado_por, setor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tipo, inicio, fim, observacao, criado_por, criado_em, atualizado_em, setor_id, nome, folga_inicio, folga_fim
`

type CriarPlantaoParams struct {
	Nome        string      `json:"nome"`
	Tipo        string      `json:"tipo"`
	Inicio      pgtype.Date `json:"inicio"`
	Fim         pgtype.Date `json:"fim"`
	Observacao  string      `json:"observacao"`
	FolgaInicio pgtype.Date `json:"folga_inicio"`
	FolgaFim    pgtype.Date `json:"folga_fim"`
	CriadoPor   pgtype.UUID `json:"criado_por"`
	SetorID     pgtype.UUID `json:"setor_id"`
}

func (q *Queries) CriarPlantao(ctx context.Context, arg CriarPlantaoParams) (Plantoes, error) {
	row := q.db.QueryRow(ctx, criarPlantao,
		arg.Nome,
		arg.Tipo,
		arg.Inicio,
		arg.Fim,
		arg.Observacao,
		arg.FolgaInicio,
		arg.FolgaFim,
		arg.CriadoPor,
		arg.SetorID,
	)
	var i Plantoes
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
		&i.Observacao,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
		&i.Nome,
		&i.FolgaInicio,
		&i.FolgaFim,
	)
	return i, err
}

const deletarPlantao = `-- name: DeletarPlantao :exec
DELETE FROM plantoes WHERE id = $1
`

func (q *Queries) DeletarPlantao(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarPlantao, id)
	return err
}

const listarPessoasPlantao = `-- name: ListarPessoasPlantao :many
SELECT DISTINCT ON (lower(nome)) nome
FROM plantoes
WHERE setor_id = $1
ORDER BY lower(nome), criado_em DESC
`

// Nomes já usados na escala do setor, para sugerir ao montar turnos
func (q *Queries) ListarPessoasPlantao(ctx context.Context, setorID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listarPessoasPlantao, setorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nome string
		if err := rows.Scan(&nome); err != nil {
			return nil, err
		}
		items = append(items, nome)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPlantoesIntervalo = `-- name: ListarPlantoesIntervalo :many
SELECT id, nome, tipo, inicio, fim, observacao, folga_inicio, folga_fim
FROM plantoes
WHERE setor_id = $1
  AND ((fim >= $2::date AND inicio <= $3::date)
    OR (folga_fim >= $2::date AND folga_inicio <= $3::date))
ORDER BY inicio, tipo, nome
`

type ListarPlantoesIntervaloParams struct {
	SetorID pgtype.UUID `json:"setor_id"`
	De      pgtype.Date `json:"de"`
	Ate     pgtype.Date `json:"ate"`
}

type ListarPlantoesIntervaloRow struct {
	ID          pgtype.UUID `json:"id"`
	Nome        string      `json:"nome"`
	Tipo        string      `json:"tipo"`
	Inicio      pgtype.Date `json:"inicio"`
	Fim         pgtype.Date `json:"fim"`
	Observacao  string      `json:"observacao"`
	FolgaInicio pgtype.Date `json:"folga_inicio"`
	FolgaFim    pgtype.Date `json:"folga_fim"`
}

// Turnos que caem no intervalo, pelo turno ou pela folga
func (q *Queries) ListarPlantoesIntervalo(ctx context.Context, arg ListarPlantoesIntervaloParams) ([]ListarPlantoesIntervaloRow, error) {
	rows, err := q.db.Query(ctx, listarPlantoesIntervalo, arg.SetorID, arg.De, arg.Ate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPlantoesIntervaloRow
	for rows.Next() {
		var i ListarPlantoesIntervaloRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Tipo,
			&i.Inicio,
			&i.Fim,
			&i.Observacao,
			&i.FolgaInicio,
			&i.FolgaFim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterPlantao = `-- name: ObterPlantao :one
SELECT id, tipo, inicio, fim, observacao, criado_por, criado_em, atualizado_em, setor_id, nome, folga_inicio, folga_fim FROM plantoes WHERE id = $1 AND setor_id = $2
`

type ObterPlantaoParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) ObterPlantao(ctx context.Context, arg ObterPlantaoParams) (Plantoes, error) {
	row := q.db.QueryRow(ctx, obterPlantao, arg.ID, arg.SetorID)
	var i Plantoes
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
		&i.Observacao,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
		&i.Nome,
		&i.FolgaInicio,
		&i.FolgaFim,
	)
	return i, err
}

const proximoPlantaoPorNome = `-- name: ProximoPlantaoPorNome :one
SELECT id, nome, tipo, inicio, fim, observacao, folga_inicio, folga_fim FROM plantoes
WHERE setor_id = $1 AND lower(nome) = lower($2) AND fim >= $3::date
ORDER BY inicio
LIMIT 1
`

type ProximoPlantaoPorNomeParams struct {
	SetorID pgtype.UUID `json:"setor_id"`
	Nome    string      `json:"nome"`
	Dia     pgtype.Date `json:"dia"`
}

type ProximoPlantaoPorNomeRow struct {
	ID          pgtype.UUID `json:"id"`
	Nome        string      `json:"nome"`
	Tipo        string      `json:"tipo"`
	Inicio      pgtype.Date `json:"inicio"`
	Fim         pgtype.Date `json:"fim"`
	Observacao  string      `json:"observacao"`
	FolgaInicio pgtype.Date `json:"folga_inicio"`
	FolgaFim    pgtype.Date `json:"folga_fim"`
}

// Turno em andamento ou o próximo de quem tem este nome na escala
func (q *Queries) ProximoPlantaoPorNome(ctx context.Context, arg ProximoPlantaoPorNomeParams) (ProximoPlantaoPorNomeRow, error) {
	row := q.db.QueryRow(ctx, proximoPlantaoPorNome, arg.SetorID, arg.Nome, arg.Dia)
	var i ProximoPlantaoPorNomeRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
		&i.Observacao,
		&i.FolgaInicio,
		&i.FolgaFim,
	)
	return i, err
}

const travarEscala = `-- name: TravarEscala :exec
SELECT pg_advisory_xact_lock(hashtext('tiiv_plantoes'))
`

// Serializa as gravações da escala para a checagem de conflito valer
func (q *Queries) TravarEscala(ctx context.Context) error {
	_, err := q.db.Exec(ctx, travarEscala)
	return err
}
