// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plantoes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarPlantao = `-- name: AtualizarPlantao :one
UPDATE plantoes
SET usuario_id = $2, tipo = $3, inicio = $4, fim = $5, observacao = $6, atualizado_em = now()
WHERE id = $1
RETURNING id, usuario_id, tipo, inicio, fim, observacao, criado_por, criado_em, atualizado_em, setor_id
`

type AtualizarPlantaoParams struct {
	ID         pgtype.UUID `json:"id"`
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	Tipo       string      `json:"tipo"`
	Inicio     pgtype.Date `json:"inicio"`
	Fim        pgtype.Date `json:"fim"`
	Observacao string      `json:"observacao"`
}

func (q *Queries) AtualizarPlantao(ctx context.Context, arg AtualizarPlantaoParams) (Plantoes, error) {
	row := q.db.QueryRow(ctx, atualizarPlantao,
		arg.ID,
		arg.UsuarioID,
		arg.Tipo,
		arg.Inicio,
		arg.Fim,
		arg.Observacao,
	)
	var i Plantoes
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
		&i.Observacao,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const buscarConflitoPlantao = `-- name: BuscarConflitoPlantao :one
SELECT p.inicio, p.fim, u.nome AS usuario_nome
FROM plantoes p
JOIN usuarios u ON u.id = p.usuario_id
WHERE p.usuario_id = $1
  AND p.tipo = $2
  AND p.fim >= $3::date
  AND p.inicio <= $4::date
  AND ($5::uuid IS NULL OR p.id <> $5)
ORDER BY p.inicio
LIMIT 1
`

type BuscarConflitoPlantaoParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Tipo      string      `json:"tipo"`
	Inicio    pgtype.Date `json:"inicio"`
	Fim       pgtype.Date `json:"fim"`
	IgnorarID pgtype.UUID `json:"ignorar_id"`
}

type BuscarConflitoPlantaoRow struct {
	Inicio      pgtype.Date `json:"inicio"`
	Fim         pgtype.Date `json:"fim"`
	UsuarioNome string      `json:"usuario_nome"`
}

// A mesma pessoa não pode ter dois turnos do mesmo tipo sobrepostos
func (q *Queries) BuscarConflitoPlantao(ctx context.Context, arg BuscarConflitoPlantaoParams) (BuscarConflitoPlantaoRow, error) {
	row := q.db.QueryRow(ctx, buscarConflitoPlantao,
		arg.UsuarioID,
		arg.Tipo,
		arg.Inicio,
		arg.Fim,
		arg.IgnorarID,
	)
	var i BuscarConflitoPlantaoRow
	err := row.Scan(&i.Inicio, &i.Fim, &i.UsuarioNome)
	return i, err
}

const criarPlantao = `-- name: CriarPlantao :one
INSERT INTO plantoes (usuario_id, tipo, inicio, fim, observacao, criado_por, setor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, usuario_id, tipo, inicio, fim, observacao, criado_por, criado_em, atualizado_em, setor_id
`

type CriarPlantaoParams struct {
	UsuarioID  pgtype.UUID `json:"usuario_id"`
	Tipo       string      `json:"tipo"`
	Inicio     pgtype.Date `json:"inicio"`
	Fim        pgtype.Date `json:"fim"`
	Observacao string      `json:"observacao"`
	CriadoPor  pgtype.UUID `json:"criado_por"`
	SetorID    pgtype.UUID `json:"setor_id"`
}

func (q *Queries) CriarPlantao(ctx context.Context, arg CriarPlantaoParams) (Plantoes, error) {
	row := q.db.QueryRow(ctx, criarPlantao,
		arg.UsuarioID,
		arg.Tipo,
		arg.Inicio,
		arg.Fim,
		arg.Observacao,
		arg.CriadoPor,
		arg.SetorID,
	)
	var i Plantoes
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
		&i.Observacao,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const deletarPlantao = `-- name: DeletarPlantao :exec
DELETE FROM plantoes WHERE id = $1
`

func (q *Queries) DeletarPlantao(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarPlantao, id)
	return err
}

const listarPlantoesIntervalo = `-- name: ListarPlantoesIntervalo :many
SELECT
    p.id, p.usuario_id, p.tipo, p.inicio, p.fim, p.observacao,
    u.nome AS usuario_nome, u.cor AS usuario_cor
FROM plantoes p
JOIN usuarios u ON u.id = p.usuario_id
WHERE p.setor_id = $1 AND p.fim >= $2::date AND p.inicio <= $3::date
ORDER BY p.inicio, p.tipo, u.nome
`

type ListarPlantoesIntervaloParams struct {
	SetorID pgtype.UUID `json:"setor_id"`
	De      pgtype.Date `json:"de"`
	Ate     pgtype.Date `json:"ate"`
}

type ListarPlantoesIntervaloRow struct {
	ID          pgtype.UUID `json:"id"`
	UsuarioID   pgtype.UUID `json:"usuario_id"`
	Tipo        string      `json:"tipo"`
	Inicio      pgtype.Date `json:"inicio"`
	Fim         pgtype.Date `json:"fim"`
	Observacao  string      `json:"observacao"`
	UsuarioNome string      `json:"usuario_nome"`
	UsuarioCor  string      `json:"usuario_cor"`
}

func (q *Queries) ListarPlantoesIntervalo(ctx context.Context, arg ListarPlantoesIntervaloParams) ([]ListarPlantoesIntervaloRow, error) {
	rows, err := q.db.Query(ctx, listarPlantoesIntervalo, arg.SetorID, arg.De, arg.Ate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPlantoesIntervaloRow
	for rows.Next() {
		var i ListarPlantoesIntervaloRow
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Tipo,
			&i.Inicio,
			&i.Fim,
			&i.Observacao,
			&i.UsuarioNome,
			&i.UsuarioCor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterPlantao = `-- name: ObterPlantao :one
SELECT id, usuario_id, tipo, inicio, fim, observacao, criado_por, criado_em, atualizado_em, setor_id FROM plantoes WHERE id = $1 AND setor_id = $2
`

type ObterPlantaoParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) ObterPlantao(ctx context.Context, arg ObterPlantaoParams) (Plantoes, error) {
	row := q.db.QueryRow(ctx, obterPlantao, arg.ID, arg.SetorID)
	var i Plantoes
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
		&i.Observacao,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const proximoPlantaoUsuario = `-- name: ProximoPlantaoUsuario :one
SELECT id, tipo, inicio, fim FROM plantoes
WHERE usuario_id = $1 AND setor_id = $2 AND fim >= $3::date
ORDER BY inicio
LIMIT 1
`

type ProximoPlantaoUsuarioParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	SetorID   pgtype.UUID `json:"setor_id"`
	Dia       pgtype.Date `json:"dia"`
}

type ProximoPlantaoUsuarioRow struct {
	ID     pgtype.UUID `json:"id"`
	Tipo   string      `json:"tipo"`
	Inicio pgtype.Date `json:"inicio"`
	Fim    pgtype.Date `json:"fim"`
}

// Turno em andamento ou o próximo da pessoa
func (q *Queries) ProximoPlantaoUsuario(ctx context.Context, arg ProximoPlantaoUsuarioParams) (ProximoPlantaoUsuarioRow, error) {
	row := q.db.QueryRow(ctx, proximoPlantaoUsuario, arg.UsuarioID, arg.SetorID, arg.Dia)
	var i ProximoPlantaoUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Inicio,
		&i.Fim,
	)
	return i, err
}

const travarEscala = `-- name: TravarEscala :exec
SELECT pg_advisory_xact_lock(hashtext('tiiv_plantoes'))
`

// Serializa as gravações da escala para a checagem de conflito valer
func (q *Queries) TravarEscala(ctx context.Context) error {
	_, err := q.db.Exec(ctx, travarEscala)
	return err
}
