// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procedimentos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarProcedimento = `-- name: AtualizarProcedimento :one
UPDATE procedimentos
SET titulo = $2, categoria = $3, corpo = $4, ativo = $5, atualizado_por = $6, atualizado_em = now()
WHERE id = $1 AND setor_id = $7
RETURNING id, titulo, categoria, corpo, ativo, criado_por, atualizado_por, criado_em, atualizado_em, setor_id
`

type AtualizarProcedimentoParams struct {
	ID            pgtype.UUID `json:"id"`
	Titulo        string      `json:"titulo"`
	Categoria     string      `json:"categoria"`
	Corpo         string      `json:"corpo"`
	Ativo         bool        `json:"ativo"`
	AtualizadoPor pgtype.UUID `json:"atualizado_por"`
	SetorID       pgtype.UUID `json:"setor_id"`
}

func (q *Queries) AtualizarProcedimento(ctx context.Context, arg AtualizarProcedimentoParams) (Procedimentos, error) {
	row := q.db.QueryRow(ctx, atualizarProcedimento,
		arg.ID,
		arg.Titulo,
		arg.Categoria,
		arg.Corpo,
		arg.Ativo,
		arg.AtualizadoPor,
		arg.SetorID,
	)
	var i Procedimentos
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Categoria,
		&i.Corpo,
		&i.Ativo,
		&i.CriadoPor,
		&i.AtualizadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const buscarProcedimentoPorID = `-- name: BuscarProcedimentoPorID :one
SELECT
    p.id, p.titulo, p.categoria, p.corpo, p.ativo, p.criado_em, p.atualizado_em,
    u.nome AS atualizado_por_nome
FROM procedimentos p
JOIN usuarios u ON u.id = p.atualizado_por
WHERE p.id = $1 AND p.setor_id = $2
`

type BuscarProcedimentoPorIDParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

type BuscarProcedimentoPorIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	Titulo            string             `json:"titulo"`
	Categoria         string             `json:"categoria"`
	Corpo             string             `json:"corpo"`
	Ativo             bool               `json:"ativo"`
	CriadoEm          pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm      pgtype.Timestamptz `json:"atualizado_em"`
	AtualizadoPorNome string             `json:"atualizado_por_nome"`
}

func (q *Queries) BuscarProcedimentoPorID(ctx context.Context, arg BuscarProcedimentoPorIDParams) (BuscarProcedimentoPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarProcedimentoPorID, arg.ID, arg.SetorID)
	var i BuscarProcedimentoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Categoria,
		&i.Corpo,
		&i.Ativo,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.AtualizadoPorNome,
	)
	return i, err
}

const buscarProcedimentosRelevantes = `-- name: BuscarProcedimentosRelevantes :many
WITH consulta AS (
    SELECT
        unaccent(lower($3::text)) AS txt,
        NULLIF(replace(plainto_tsquery('portuguese', unaccent(lower($3::text)))::text, ' & ', ' | '), '')::tsquery AS tsq
)
SELECT p.id, p.titulo, p.categoria, p.corpo, pontos.relevancia
FROM procedimentos p
CROSS JOIN consulta c
CROSS JOIN LATERAL (
    SELECT (
        COALESCE(ts_rank(
            setweight(to_tsvector('portuguese', unaccent(lower(p.titulo))), 'A') ||
            setweight(to_tsvector('portuguese', unaccent(lower(p.categoria || ' ' || p.corpo))), 'B'),
            c.tsq
        ), 0) +
        word_similarity(c.txt, unaccent(lower(p.titulo || ' ' || p.corpo)))
    )::float8 AS relevancia
) pontos
WHERE p.ativo AND p.setor_id = $1
ORDER BY pontos.relevancia DESC
LIMIT $2::int
`

type BuscarProcedimentosRelevantesParams struct {
	SetorID pgtype.UUID `json:"setor_id"`
	Limite  int32       `json:"limite"`
	Texto   string      `json:"texto"`
}

type BuscarProcedimentosRelevantesRow struct {
	ID         pgtype.UUID `json:"id"`
	Titulo     string      `json:"titulo"`
	Categoria  string      `json:"categoria"`
	Corpo      string      `json:"corpo"`
	Relevancia float64     `json:"relevancia"`
}

// Busca para o tira-dúvidas: full-text em português (termos em OU) somado à
// semelhança por trigramas, que tolera erros de digitação.
func (q *Queries) BuscarProcedimentosRelevantes(ctx context.Context, arg BuscarProcedimentosRelevantesParams) ([]BuscarProcedimentosRelevantesRow, error) {
	rows, err := q.db.Query(ctx, buscarProcedimentosRelevantes, arg.SetorID, arg.Limite, arg.Texto)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuscarProcedimentosRelevantesRow
	for rows.Next() {
		var i BuscarProcedimentosRelevantesRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Categoria,
			&i.Corpo,
			&i.Relevancia,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const buscarRevisaoProcedimento = `-- name: BuscarRevisaoProcedimento :one
SELECT r.id, r.procedimento_id, r.titulo, r.categoria, r.corpo, r.ativo, r.nota, r.editado_por, r.criado_em FROM procedimento_revisoes r
JOIN procedimentos p ON p.id = r.procedimento_id
WHERE r.id = $1 AND r.procedimento_id = $2 AND p.setor_id = $3
`

type BuscarRevisaoProcedimentoParams struct {
	ID             pgtype.UUID `json:"id"`
	ProcedimentoID pgtype.UUID `json:"procedimento_id"`
	SetorID        pgtype.UUID `json:"setor_id"`
}

func (q *Queries) BuscarRevisaoProcedimento(ctx context.Context, arg BuscarRevisaoProcedimentoParams) (ProcedimentoRevisoes, error) {
	row := q.db.QueryRow(ctx, buscarRevisaoProcedimento, arg.ID, arg.ProcedimentoID, arg.SetorID)
	var i ProcedimentoRevisoes
	err := row.Scan(
		&i.ID,
		&i.ProcedimentoID,
		&i.Titulo,
		&i.Categoria,
		&i.Corpo,
		&i.Ativo,
		&i.Nota,
		&i.EditadoPor,
		&i.CriadoEm,
	)
	return i, err
}

const criarProcedimento = `-- name: CriarProcedimento :one
INSERT INTO procedimentos (titulo, categoria, corpo, ativo, criado_por, atualizado_por, setor_id)
VALUES ($1, $2, $3, $4, $5, $5, $6)
RETURNING id, titulo, categoria, corpo, ativo, criado_por, atualizado_por, criado_em, atualizado_em, setor_id
`

type CriarProcedimentoParams struct {
	Titulo    string      `json:"titulo"`
	Categoria string      `json:"categoria"`
	Corpo     string      `json:"corpo"`
	Ativo     bool        `json:"ativo"`
	CriadoPor pgtype.UUID `json:"criado_por"`
	SetorID   pgtype.UUID `json:"setor_id"`
}

func (q *Queries) CriarProcedimento(ctx context.Context, arg CriarProcedimentoParams) (Procedimentos, error) {
	row := q.db.QueryRow(ctx, criarProcedimento,
		arg.Titulo,
		arg.Categoria,
		arg.Corpo,
		arg.Ativo,
		arg.CriadoPor,
		arg.SetorID,
	)
	var i Procedimentos
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Categoria,
		&i.Corpo,
		&i.Ativo,
		&i.CriadoPor,
		&i.AtualizadoPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.SetorID,
	)
	return i, err
}

const criarRevisaoProcedimento = `-- name: CriarRevisaoProcedimento :exec
INSERT INTO procedimento_revisoes (procedimento_id, titulo, categoria, corpo, ativo, nota, editado_por)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CriarRevisaoProcedimentoParams struct {
	ProcedimentoID pgtype.UUID `json:"procedimento_id"`
	Titulo         string      `json:"titulo"`
	Categoria      string      `json:"categoria"`
	Corpo          string      `json:"corpo"`
	Ativo          bool        `json:"ativo"`
	Nota           string      `json:"nota"`
	EditadoPor     pgtype.UUID `json:"editado_por"`
}

func (q *Queries) CriarRevisaoProcedimento(ctx context.Context, arg CriarRevisaoProcedimentoParams) error {
	_, err := q.db.Exec(ctx, criarRevisaoProcedimento,
		arg.ProcedimentoID,
		arg.Titulo,
		arg.Categoria,
		arg.Corpo,
		arg.Ativo,
		arg.Nota,
		arg.EditadoPor,
	)
	return err
}

const listarCategoriasProcedimentos = `-- name: ListarCategoriasProcedimentos :many
SELECT DISTINCT categoria
FROM procedimentos
WHERE categoria <> '' AND setor_id = $1
ORDER BY categoria ASC
`

func (q *Queries) ListarCategoriasProcedimentos(ctx context.Context, setorID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listarCategoriasProcedimentos, setorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var categoria string
		if err := rows.Scan(&categoria); err != nil {
			return nil, err
		}
		items = append(items, categoria)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarProcedimentos = `-- name: ListarProcedimentos :many
SELECT
    p.id, p.titulo, p.categoria, p.ativo, p.atualizado_em,
    u.nome AS atualizado_por_nome
FROM procedimentos p
JOIN usuarios u ON u.id = p.atualizado_por
WHERE
    p.setor_id = $1
    AND ($2::text IS NULL OR
     unaccent(lower(p.titulo || ' ' || p.categoria || ' ' || p.corpo)) ILIKE '%' || unaccent(lower($2)) || '%')
    AND ($3::text IS NULL OR p.categoria = $3)
    AND ($4::boolean IS NULL OR p.ativo = $4)
ORDER BY p.ativo DESC, p.categoria ASC, p.titulo ASC
`

type ListarProcedimentosParams struct {
	SetorID   pgtype.UUID `json:"setor_id"`
	Busca     pgtype.Text `json:"busca"`
	Categoria pgtype.Text `json:"categoria"`
	Ativo     pgtype.Bool `json:"ativo"`
}

type ListarProcedimentosRow struct {
	ID                pgtype.UUID        `json:"id"`
	Titulo            string             `json:"titulo"`
	Categoria         string             `json:"categoria"`
	Ativo             bool               `json:"ativo"`
	AtualizadoEm      pgtype.Timestamptz `json:"atualizado_em"`
	AtualizadoPorNome string             `json:"atualizado_por_nome"`
}

func (q *Queries) ListarProcedimentos(ctx context.Context, arg ListarProcedimentosParams) ([]ListarProcedimentosRow, error) {
	rows, err := q.db.Query(ctx, listarProcedimentos,
		arg.SetorID,
		arg.Busca,
		arg.Categoria,
		arg.Ativo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarProcedimentosRow
	for rows.Next() {
		var i ListarProcedimentosRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Categoria,
			&i.Ativo,
			&i.AtualizadoEm,
			&i.AtualizadoPorNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarRevisoesProcedimento = `-- name: ListarRevisoesProcedimento :many
SELECT
    r.id, r.titulo, r.categoria, r.corpo, r.ativo, r.nota, r.criado_em,
    u.nome AS editado_por_nome
FROM procedimento_revisoes r
JOIN usuarios u ON u.id = r.editado_por
JOIN procedimentos p ON p.id = r.procedimento_id
WHERE r.procedimento_id = $1 AND p.setor_id = $2
ORDER BY r.criado_em DESC
`

type ListarRevisoesProcedimentoParams struct {
	ProcedimentoID pgtype.UUID `json:"procedimento_id"`
	SetorID        pgtype.UUID `json:"setor_id"`
}

type ListarRevisoesProcedimentoRow struct {
	ID             pgtype.UUID        `json:"id"`
	Titulo         string             `json:"titulo"`
	Categoria      string             `json:"categoria"`
	Corpo          string             `json:"corpo"`
	Ativo          bool               `json:"ativo"`
	Nota           string             `json:"nota"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	EditadoPorNome string             `json:"editado_por_nome"`
}

func (q *Queries) ListarRevisoesProcedimento(ctx context.Context, arg ListarRevisoesProcedimentoParams) ([]ListarRevisoesProcedimentoRow, error) {
	rows, err := q.db.Query(ctx, listarRevisoesProcedimento, arg.ProcedimentoID, arg.SetorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarRevisoesProcedimentoRow
	for rows.Next() {
		var i ListarRevisoesProcedimentoRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Categoria,
			&i.Corpo,
			&i.Ativo,
			&i.Nota,
			&i.CriadoEm,
			&i.EditadoPorNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obterUsoAssistente = `-- name: ObterUsoAssistente :one
SELECT neurons::float8 AS neurons, perguntas FROM assistente_uso
WHERE dia = (now() AT TIME ZONE 'UTC')::date
`

type ObterUsoAssistenteRow struct {
	Neurons   float64 `json:"neurons"`
	Perguntas int32   `json:"perguntas"`
}

func (q *Queries) ObterUsoAssistente(ctx context.Context) (ObterUsoAssistenteRow, error) {
	row := q.db.QueryRow(ctx, obterUsoAssistente)
	var i ObterUsoAssistenteRow
	err := row.Scan(&i.Neurons, &i.Perguntas)
	return i, err
}

const registrarUsoAssistente = `-- name: RegistrarUsoAssistente :exec
INSERT INTO assistente_uso (dia, neurons, perguntas)
VALUES ((now() AT TIME ZONE 'UTC')::date, $1::float8, 1)
ON CONFLICT (dia) DO UPDATE
SET neurons = assistente_uso.neurons + EXCLUDED.neurons,
    perguntas = assistente_uso.perguntas + 1
`

func (q *Queries) RegistrarUsoAssistente(ctx context.Context, neurons float64) error {
	_, err := q.db.Exec(ctx, registrarUsoAssistente, neurons)
	return err
}
