// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbrirQueda(ctx context.Context, arg AbrirQuedaParams) (pgtype.UUID, error)
	// Só entra quem é do setor do evento (ou quem o criou)
	AdicionarParticipanteEvento(ctx context.Context, arg AdicionarParticipanteEventoParams) error
	AtualizarAtividadesRegistro(ctx context.Context, arg AtualizarAtividadesRegistroParams) (TecnicoRegistros, error)
	AtualizarAviso(ctx context.Context, arg AtualizarAvisoParams) (Avisos, error)
	AtualizarEvento(ctx context.Context, arg AtualizarEventoParams) (Eventos, error)
	AtualizarItemEstoque(ctx context.Context, arg AtualizarItemEstoqueParams) (ItensEstoque, error)
	AtualizarLink(ctx context.Context, arg AtualizarLinkParams) (Links, error)
	AtualizarMonitor(ctx context.Context, arg AtualizarMonitorParams) (Monitores, error)
	AtualizarPin(ctx context.Context, arg AtualizarPinParams) (pgtype.UUID, error)
	AtualizarPlantao(ctx context.Context, arg AtualizarPlantaoParams) (Plantoes, error)
	AtualizarProcedimento(ctx context.Context, arg AtualizarProcedimentoParams) (Procedimentos, error)
	// Troca feita pelo próprio usuário: cumpre a troca obrigatória e zera as tentativas
	AtualizarProprioPin(ctx context.Context, arg AtualizarProprioPinParams) error
	AtualizarRegistroTecnico(ctx context.Context, arg AtualizarRegistroTecnicoParams) (TecnicoRegistros, error)
	AtualizarSaldoItemEstoque(ctx context.Context, arg AtualizarSaldoItemEstoqueParams) (ItensEstoque, error)
	AtualizarSetor(ctx context.Context, arg AtualizarSetorParams) (Setores, error)
	AtualizarStatusTarefa(ctx context.Context, arg AtualizarStatusTarefaParams) (Tarefas, error)
	AtualizarTarefa(ctx context.Context, arg AtualizarTarefaParams) (Tarefas, error)
	AtualizarTecnico(ctx context.Context, arg AtualizarTecnicoParams) (Tecnicos, error)
	AtualizarTemaUsuario(ctx context.Context, arg AtualizarTemaUsuarioParams) (AtualizarTemaUsuarioRow, error)
	AtualizarUltimoUsoSessao(ctx context.Context, arg AtualizarUltimoUsoSessaoParams) error
	AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (AtualizarUsuarioRow, error)
	BloquearItemEstoqueParaAtualizacao(ctx context.Context, id pgtype.UUID) (ItensEstoque, error)
	BloquearMonitor(ctx context.Context, id pgtype.UUID) (Monitores, error)
	BloquearTicket(ctx context.Context, arg BloquearTicketParams) (Tickets, error)
	BuscarComentarioPorID(ctx context.Context, id pgtype.UUID) (TarefaComentarios, error)
	// Ninguém trabalha na própria folga: nem turno novo sobre uma folga já
	// marcada, nem folga nova sobre um turno já marcado (de qualquer tipo)
	BuscarConflitoFolga(ctx context.Context, arg BuscarConflitoFolgaParams) (BuscarConflitoFolgaRow, error)
	// A mesma pessoa (pelo nome, sem diferenciar maiúsculas) não pode ter dois
	// turnos do mesmo tipo sobrepostos no setor
	BuscarConflitoPlantao(ctx context.Context, arg BuscarConflitoPlantaoParams) (BuscarConflitoPlantaoRow, error)
	BuscarEventoPorID(ctx context.Context, arg BuscarEventoPorIDParams) (BuscarEventoPorIDRow, error)
	BuscarItemEstoquePorID(ctx context.Context, id pgtype.UUID) (ItensEstoque, error)
	BuscarProcedimentoPorID(ctx context.Context, arg BuscarProcedimentoPorIDParams) (BuscarProcedimentoPorIDRow, error)
	// Busca para o tira-dúvidas: full-text em português (termos em OU) somado à
	// semelhança por trigramas, que tolera erros de digitação.
	BuscarProcedimentosRelevantes(ctx context.Context, arg BuscarProcedimentosRelevantesParams) ([]BuscarProcedimentosRelevantesRow, error)
	BuscarRegistroTecnicoPorID(ctx context.Context, arg BuscarRegistroTecnicoPorIDParams) (TecnicoRegistros, error)
	BuscarRevisaoProcedimento(ctx context.Context, arg BuscarRevisaoProcedimentoParams) (ProcedimentoRevisoes, error)
	// Setor de trabalho: o escolhido na sessão (só superadmin) ou o do usuário
	BuscarSessaoPorHash(ctx context.Context, tokenHash string) (BuscarSessaoPorHashRow, error)
	BuscarSetor(ctx context.Context, id pgtype.UUID) (Setores, error)
	BuscarTarefaPorID(ctx context.Context, arg BuscarTarefaPorIDParams) (BuscarTarefaPorIDRow, error)
	BuscarTecnicoPorID(ctx context.Context, arg BuscarTecnicoPorIDParams) (BuscarTecnicoPorIDRow, error)
	BuscarTelaTVPorHash(ctx context.Context, chaveHash string) (BuscarTelaTVPorHashRow, error)
	BuscarUsuarioPorID(ctx context.Context, id pgtype.UUID) (BuscarUsuarioPorIDRow, error)
	BuscarUsuarioPorIDComPin(ctx context.Context, id pgtype.UUID) (BuscarUsuarioPorIDComPinRow, error)
	ContarMovimentacoesItem(ctx context.Context, itemID pgtype.UUID) (int64, error)
	ContarRegistrosTecnicos(ctx context.Context, arg ContarRegistrosTecnicosParams) (int64, error)
	ContarSuperadminsAtivos(ctx context.Context) (int64, error)
	ContarTicketsAbertos(ctx context.Context, setorID pgtype.UUID) (int64, error)
	ContarUsuarios(ctx context.Context) (int64, error)
	CriarAviso(ctx context.Context, arg CriarAvisoParams) (Avisos, error)
	CriarComentarioTarefa(ctx context.Context, arg CriarComentarioTarefaParams) (TarefaComentarios, error)
	CriarEvento(ctx context.Context, arg CriarEventoParams) (Eventos, error)
	CriarItemEstoque(ctx context.Context, arg CriarItemEstoqueParams) (ItensEstoque, error)
	CriarLink(ctx context.Context, arg CriarLinkParams) (Links, error)
	CriarMonitor(ctx context.Context, arg CriarMonitorParams) (Monitores, error)
	CriarMovimentacaoEstoque(ctx context.Context, arg CriarMovimentacaoEstoqueParams) (MovimentacoesEstoque, error)
	CriarPlantao(ctx context.Context, arg CriarPlantaoParams) (Plantoes, error)
	CriarProcedimento(ctx context.Context, arg CriarProcedimentoParams) (Procedimentos, error)
	CriarRevisaoProcedimento(ctx context.Context, arg CriarRevisaoProcedimentoParams) error
	CriarSessao(ctx context.Context, arg CriarSessaoParams) (CriarSessaoRow, error)
	CriarSetor(ctx context.Context, arg CriarSetorParams) (Setores, error)
	CriarTarefa(ctx context.Context, arg CriarTarefaParams) (Tarefas, error)
	CriarTecnico(ctx context.Context, arg CriarTecnicoParams) (Tecnicos, error)
	CriarTelaTV(ctx context.Context, arg CriarTelaTVParams) (TelasTv, error)
	CriarTicket(ctx context.Context, arg CriarTicketParams) (Tickets, error)
	CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error)
	DefinirSetorSessao(ctx context.Context, arg DefinirSetorSessaoParams) error
	DeletarAviso(ctx context.Context, id pgtype.UUID) error
	DeletarComentarioTarefa(ctx context.Context, id pgtype.UUID) error
	DeletarEvento(ctx context.Context, id pgtype.UUID) error
	DeletarItemEstoque(ctx context.Context, id pgtype.UUID) error
	DeletarLink(ctx context.Context, id pgtype.UUID) error
	DeletarMonitor(ctx context.Context, id pgtype.UUID) error
	DeletarOutrasSessoesUsuario(ctx context.Context, arg DeletarOutrasSessoesUsuarioParams) error
	DeletarPlantao(ctx context.Context, id pgtype.UUID) error
	DeletarRegistroTecnico(ctx context.Context, id pgtype.UUID) error
	DeletarSessaoPorHash(ctx context.Context, tokenHash string) error
	DeletarSessoesExpiradas(ctx context.Context) error
	DeletarSessoesPorUsuario(ctx context.Context, usuarioID pgtype.UUID) error
	DeletarSetor(ctx context.Context, id pgtype.UUID) (int64, error)
	DeletarTarefa(ctx context.Context, id pgtype.UUID) error
	DeletarTelaTV(ctx context.Context, arg DeletarTelaTVParams) (int64, error)
	DesativarItemEstoque(ctx context.Context, id pgtype.UUID) error
	DesbloquearUsuario(ctx context.Context, id pgtype.UUID) (DesbloquearUsuarioRow, error)
	FecharQuedaAberta(ctx context.Context, monitorID pgtype.UUID) error
	ListarAvisosAtivos(ctx context.Context, setorID pgtype.UUID) ([]ListarAvisosAtivosRow, error)
	ListarCategoriasEstoque(ctx context.Context) ([]string, error)
	ListarCategoriasProcedimentos(ctx context.Context, setorID pgtype.UUID) ([]string, error)
	ListarComentariosTarefa(ctx context.Context, tarefaID pgtype.UUID) ([]ListarComentariosTarefaRow, error)
	// Operadores ativos do setor (responsável de tarefa, participantes, escala)
	ListarEquipeSetor(ctx context.Context, setorID pgtype.UUID) ([]ListarEquipeSetorRow, error)
	ListarEventosIntervalo(ctx context.Context, arg ListarEventosIntervaloParams) ([]ListarEventosIntervaloRow, error)
	ListarItensAbaixoDoMinimo(ctx context.Context) ([]ItensEstoque, error)
	ListarItensEstoque(ctx context.Context, arg ListarItensEstoqueParams) ([]ListarItensEstoqueRow, error)
	ListarLinks(ctx context.Context, setorID pgtype.UUID) ([]ListarLinksRow, error)
	ListarMonitores(ctx context.Context) ([]Monitores, error)
	ListarMonitoresOffline(ctx context.Context) ([]ListarMonitoresOfflineRow, error)
	ListarMonitoresParaVerificar(ctx context.Context) ([]Monitores, error)
	ListarMovimentacoesEstoque(ctx context.Context, arg ListarMovimentacoesEstoqueParams) ([]ListarMovimentacoesEstoqueRow, error)
	ListarParticipantesPorEvento(ctx context.Context, eventoID pgtype.UUID) ([]ListarParticipantesPorEventoRow, error)
	ListarParticipantesPorEventos(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListarParticipantesPorEventosRow, error)
	// Nomes já usados na escala do setor, para sugerir ao montar turnos
	ListarPessoasPlantao(ctx context.Context, setorID pgtype.UUID) ([]string, error)
	// Turnos que caem no intervalo, pelo turno ou pela folga
	ListarPlantoesIntervalo(ctx context.Context, arg ListarPlantoesIntervaloParams) ([]ListarPlantoesIntervaloRow, error)
	ListarProcedimentos(ctx context.Context, arg ListarProcedimentosParams) ([]ListarProcedimentosRow, error)
	ListarQuedasMonitor(ctx context.Context, monitorID pgtype.UUID) ([]ListarQuedasMonitorRow, error)
	ListarRegistrosTecnicos(ctx context.Context, arg ListarRegistrosTecnicosParams) ([]ListarRegistrosTecnicosRow, error)
	ListarRevisoesProcedimento(ctx context.Context, arg ListarRevisoesProcedimentoParams) ([]ListarRevisoesProcedimentoRow, error)
	ListarSetores(ctx context.Context) ([]ListarSetoresRow, error)
	// Setores que aparecem na tela de acesso (ticket e tira-dúvidas)
	ListarSetoresPedidos(ctx context.Context) ([]ListarSetoresPedidosRow, error)
	ListarTarefas(ctx context.Context, arg ListarTarefasParams) ([]ListarTarefasRow, error)
	ListarTarefasPendentesUsuario(ctx context.Context, arg ListarTarefasPendentesUsuarioParams) ([]ListarTarefasPendentesUsuarioRow, error)
	ListarTecnicos(ctx context.Context, arg ListarTecnicosParams) ([]ListarTecnicosRow, error)
	ListarTelasTV(ctx context.Context, setorID pgtype.UUID) ([]ListarTelasTVRow, error)
	ListarTickets(ctx context.Context, arg ListarTicketsParams) ([]ListarTicketsRow, error)
	ListarTodosUsuarios(ctx context.Context, setorID pgtype.UUID) ([]ListarTodosUsuariosRow, error)
	ListarUsuariosAtivos(ctx context.Context) ([]ListarUsuariosAtivosRow, error)
	MarcarTicketTratado(ctx context.Context, arg MarcarTicketTratadoParams) (Tickets, error)
	MarcarTrocaPinObrigatoria(ctx context.Context, id pgtype.UUID) error
	ObterAviso(ctx context.Context, arg ObterAvisoParams) (Avisos, error)
	ObterFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) (ObterFotoUsuarioRow, error)
	ObterLink(ctx context.Context, arg ObterLinkParams) (Links, error)
	ObterMonitor(ctx context.Context, id pgtype.UUID) (Monitores, error)
	ObterPlantao(ctx context.Context, arg ObterPlantaoParams) (Plantoes, error)
	ObterUltimaMovimentacaoItem(ctx context.Context, itemID pgtype.UUID) (MovimentacoesEstoque, error)
	ObterUsoAssistente(ctx context.Context) (ObterUsoAssistenteRow, error)
	ObterVersaoFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Timestamptz, error)
	PrimeiroSetor(ctx context.Context) (Setores, error)
	// Turno em andamento ou o próximo de quem tem este nome na escala
	ProximoPlantaoPorNome(ctx context.Context, arg ProximoPlantaoPorNomeParams) (ProximoPlantaoPorNomeRow, error)
	// Grava no máximo uma vez por minuto (a TV consulta a cada poucos segundos)
	RegistrarAcessoTelaTV(ctx context.Context, arg RegistrarAcessoTelaTVParams) error
	RegistrarEntradaTecnico(ctx context.Context, arg RegistrarEntradaTecnicoParams) (TecnicoRegistros, error)
	RegistrarSaidaTecnico(ctx context.Context, arg RegistrarSaidaTecnicoParams) (TecnicoRegistros, error)
	RegistrarUsoAssistente(ctx context.Context, neurons float64) error
	RegistrarVerificacao(ctx context.Context, arg RegistrarVerificacaoParams) error
	// Depois de trocar o alvo ou desligar: a próxima verificação decide de novo.
	ReiniciarEstadoMonitor(ctx context.Context, id pgtype.UUID) error
	// Consolidado por técnico no período (pela data de entrada). Registros ainda
	// em aberto contam como visita, mas não somam horas.
	RelatorioTecnicos(ctx context.Context, arg RelatorioTecnicosParams) ([]RelatorioTecnicosRow, error)
	RemoverFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) error
	RemoverParticipantesEvento(ctx context.Context, eventoID pgtype.UUID) error
	// Conta a tentativa ANTES de comparar o PIN, numa única instrução atômica:
	// requisições simultâneas não passam juntas pela checagem de bloqueio.
	// Sem linha retornada = usuário inexistente, inativo ou bloqueado.
	// A contagem recomeça após 15 min sem tentativas ou ao fim de um bloqueio
	// (o WHERE garante que bloqueado_ate, se preenchido, já expirou). A 5ª
	// tentativa seguida bloqueia por 5 min, 15 min, 45 min e depois 1 h.
	ReservarTentativaPin(ctx context.Context, id pgtype.UUID) (ReservarTentativaPinRow, error)
	ResumoMonitores(ctx context.Context) (ResumoMonitoresRow, error)
	SalvarFotoUsuario(ctx context.Context, arg SalvarFotoUsuarioParams) (pgtype.Timestamptz, error)
	// Tempo em queda de cada monitor dentro das últimas 24 horas
	SegundosForaUltimas24h(ctx context.Context) ([]SegundosForaUltimas24hRow, error)
	// Serializa as gravações da escala para a checagem de conflito valer
	TravarEscala(ctx context.Context) error
	UsuarioAtivoNoSetor(ctx context.Context, arg UsuarioAtivoNoSetorParams) (bool, error)
	VincularTicketQueda(ctx context.Context, arg VincularTicketQuedaParams) error
	ZerarTentativasFalhas(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
