// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbrirQueda(ctx context.Context, arg AbrirQuedaParams) (pgtype.UUID, error)
	AdicionarParticipanteEvento(ctx context.Context, arg AdicionarParticipanteEventoParams) error
	AtualizarAtividadesRegistro(ctx context.Context, arg AtualizarAtividadesRegistroParams) (TecnicoRegistros, error)
	AtualizarAviso(ctx context.Context, arg AtualizarAvisoParams) (Avisos, error)
	AtualizarEvento(ctx context.Context, arg AtualizarEventoParams) (Eventos, error)
	AtualizarItemEstoque(ctx context.Context, arg AtualizarItemEstoqueParams) (ItensEstoque, error)
	AtualizarLink(ctx context.Context, arg AtualizarLinkParams) (Links, error)
	AtualizarMonitor(ctx context.Context, arg AtualizarMonitorParams) (Monitores, error)
	AtualizarPin(ctx context.Context, arg AtualizarPinParams) (pgtype.UUID, error)
	AtualizarPlantao(ctx context.Context, arg AtualizarPlantaoParams) (Plantoes, error)
	AtualizarProcedimento(ctx context.Context, arg AtualizarProcedimentoParams) (Procedimentos, error)
	// Troca feita pelo próprio usuário: cumpre a troca obrigatória e zera as tentativas
	AtualizarProprioPin(ctx context.Context, arg AtualizarProprioPinParams) error
	AtualizarRegistroTecnico(ctx context.Context, arg AtualizarRegistroTecnicoParams) (TecnicoRegistros, error)
	AtualizarSaldoItemEstoque(ctx context.Context, arg AtualizarSaldoItemEstoqueParams) (ItensEstoque, error)
	AtualizarStatusTarefa(ctx context.Context, arg AtualizarStatusTarefaParams) (Tarefas, error)
	AtualizarTarefa(ctx context.Context, arg AtualizarTarefaParams) (Tarefas, error)
	AtualizarTecnico(ctx context.Context, arg AtualizarTecnicoParams) (Tecnicos, error)
	AtualizarTemaUsuario(ctx context.Context, arg AtualizarTemaUsuarioParams) (AtualizarTemaUsuarioRow, error)
	AtualizarUltimoUsoSessao(ctx context.Context, arg AtualizarUltimoUsoSessaoParams) error
	AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (AtualizarUsuarioRow, error)
	BloquearItemEstoqueParaAtualizacao(ctx context.Context, id pgtype.UUID) (ItensEstoque, error)
	BloquearMonitor(ctx context.Context, id pgtype.UUID) (Monitores, error)
	BloquearTicket(ctx context.Context, id pgtype.UUID) (Tickets, error)
	BuscarComentarioPorID(ctx context.Context, id pgtype.UUID) (TarefaComentarios, error)
	// A mesma pessoa não pode ter dois turnos do mesmo tipo sobrepostos
	BuscarConflitoPlantao(ctx context.Context, arg BuscarConflitoPlantaoParams) (BuscarConflitoPlantaoRow, error)
	BuscarEventoPorID(ctx context.Context, id pgtype.UUID) (Eventos, error)
	BuscarItemEstoquePorID(ctx context.Context, id pgtype.UUID) (ItensEstoque, error)
	BuscarProcedimentoPorID(ctx context.Context, id pgtype.UUID) (BuscarProcedimentoPorIDRow, error)
	// Busca para o tira-dúvidas: full-text em português (termos em OU) somado à
	// semelhança por trigramas, que tolera erros de digitação.
	BuscarProcedimentosRelevantes(ctx context.Context, arg BuscarProcedimentosRelevantesParams) ([]BuscarProcedimentosRelevantesRow, error)
	BuscarRegistroTecnicoPorID(ctx context.Context, id pgtype.UUID) (TecnicoRegistros, error)
	BuscarRevisaoProcedimento(ctx context.Context, arg BuscarRevisaoProcedimentoParams) (ProcedimentoRevisoes, error)
	BuscarSessaoPorHash(ctx context.Context, tokenHash string) (BuscarSessaoPorHashRow, error)
	BuscarTarefaPorID(ctx context.Context, id pgtype.UUID) (BuscarTarefaPorIDRow, error)
	BuscarTecnicoPorID(ctx context.Context, id pgtype.UUID) (Tecnicos, error)
	BuscarUsuarioPorID(ctx context.Context, id pgtype.UUID) (BuscarUsuarioPorIDRow, error)
	BuscarUsuarioPorIDComPin(ctx context.Context, id pgtype.UUID) (BuscarUsuarioPorIDComPinRow, error)
	ContarAdminsAtivos(ctx context.Context) (int64, error)
	ContarMovimentacoesItem(ctx context.Context, itemID pgtype.UUID) (int64, error)
	ContarRegistrosTecnicos(ctx context.Context, arg ContarRegistrosTecnicosParams) (int64, error)
	ContarTicketsAbertos(ctx context.Context) (int64, error)
	ContarUsuarios(ctx context.Context) (int64, error)
	CriarAviso(ctx context.Context, arg CriarAvisoParams) (Avisos, error)
	CriarComentarioTarefa(ctx context.Context, arg CriarComentarioTarefaParams) (TarefaComentarios, error)
	CriarEvento(ctx context.Context, arg CriarEventoParams) (Eventos, error)
	CriarItemEstoque(ctx context.Context, arg CriarItemEstoqueParams) (ItensEstoque, error)
	CriarLink(ctx context.Context, arg CriarLinkParams) (Links, error)
	CriarMonitor(ctx context.Context, arg CriarMonitorParams) (Monitores, error)
	CriarMovimentacaoEstoque(ctx context.Context, arg CriarMovimentacaoEstoqueParams) (MovimentacoesEstoque, error)
	CriarPlantao(ctx context.Context, arg CriarPlantaoParams) (Plantoes, error)
	CriarProcedimento(ctx context.Context, arg CriarProcedimentoParams) (Procedimentos, error)
	CriarRevisaoProcedimento(ctx context.Context, arg CriarRevisaoProcedimentoParams) error
	CriarSessao(ctx context.Context, arg CriarSessaoParams) (Sessoes, error)
	CriarTarefa(ctx context.Context, arg CriarTarefaParams) (Tarefas, error)
	CriarTecnico(ctx context.Context, arg CriarTecnicoParams) (Tecnicos, error)
	CriarTicket(ctx context.Context, arg CriarTicketParams) (Tickets, error)
	CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error)
	DeletarAviso(ctx context.Context, id pgtype.UUID) error
	DeletarComentarioTarefa(ctx context.Context, id pgtype.UUID) error
	DeletarEvento(ctx context.Context, id pgtype.UUID) error
	DeletarItemEstoque(ctx context.Context, id pgtype.UUID) error
	DeletarLink(ctx context.Context, id pgtype.UUID) error
	DeletarMonitor(ctx context.Context, id pgtype.UUID) error
	DeletarOutrasSessoesUsuario(ctx context.Context, arg DeletarOutrasSessoesUsuarioParams) error
	DeletarPlantao(ctx context.Context, id pgtype.UUID) error
	DeletarRegistroTecnico(ctx context.Context, id pgtype.UUID) error
	DeletarSessaoPorHash(ctx context.Context, tokenHash string) error
	DeletarSessoesExpiradas(ctx context.Context) error
	DeletarSessoesPorUsuario(ctx context.Context, usuarioID pgtype.UUID) error
	DeletarTarefa(ctx context.Context, id pgtype.UUID) error
	DesativarItemEstoque(ctx context.Context, id pgtype.UUID) error
	DesbloquearUsuario(ctx context.Context, id pgtype.UUID) (DesbloquearUsuarioRow, error)
	FecharQuedaAberta(ctx context.Context, monitorID pgtype.UUID) error
	ListarAvisosAtivos(ctx context.Context) ([]ListarAvisosAtivosRow, error)
	ListarCategoriasEstoque(ctx context.Context) ([]string, error)
	ListarCategoriasProcedimentos(ctx context.Context) ([]string, error)
	ListarComentariosTarefa(ctx context.Context, tarefaID pgtype.UUID) ([]ListarComentariosTarefaRow, error)
	ListarEventosIntervalo(ctx context.Context, arg ListarEventosIntervaloParams) ([]ListarEventosIntervaloRow, error)
	ListarItensAbaixoDoMinimo(ctx context.Context) ([]ItensEstoque, error)
	ListarItensEstoque(ctx context.Context, arg ListarItensEstoqueParams) ([]ListarItensEstoqueRow, error)
	ListarLinks(ctx context.Context) ([]ListarLinksRow, error)
	ListarMonitores(ctx context.Context) ([]Monitores, error)
	ListarMonitoresOffline(ctx context.Context) ([]ListarMonitoresOfflineRow, error)
	ListarMonitoresParaVerificar(ctx context.Context) ([]Monitores, error)
	ListarMovimentacoesEstoque(ctx context.Context, arg ListarMovimentacoesEstoqueParams) ([]ListarMovimentacoesEstoqueRow, error)
	ListarParticipantesPorEvento(ctx context.Context, eventoID pgtype.UUID) ([]ListarParticipantesPorEventoRow, error)
	ListarParticipantesPorEventos(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListarParticipantesPorEventosRow, error)
	ListarPlantoesIntervalo(ctx context.Context, arg ListarPlantoesIntervaloParams) ([]ListarPlantoesIntervaloRow, error)
	ListarProcedimentos(ctx context.Context, arg ListarProcedimentosParams) ([]ListarProcedimentosRow, error)
	ListarQuedasMonitor(ctx context.Context, monitorID pgtype.UUID) ([]ListarQuedasMonitorRow, error)
	ListarRegistrosTecnicos(ctx context.Context, arg ListarRegistrosTecnicosParams) ([]ListarRegistrosTecnicosRow, error)
	ListarRevisoesProcedimento(ctx context.Context, procedimentoID pgtype.UUID) ([]ListarRevisoesProcedimentoRow, error)
	ListarTarefas(ctx context.Context, arg ListarTarefasParams) ([]ListarTarefasRow, error)
	ListarTarefasPendentesUsuario(ctx context.Context, responsavelID pgtype.UUID) ([]ListarTarefasPendentesUsuarioRow, error)
	ListarTecnicos(ctx context.Context, ativo pgtype.Bool) ([]ListarTecnicosRow, error)
	ListarTickets(ctx context.Context, status pgtype.Text) ([]ListarTicketsRow, error)
	ListarTodosUsuarios(ctx context.Context) ([]ListarTodosUsuariosRow, error)
	ListarUsuariosAtivos(ctx context.Context) ([]ListarUsuariosAtivosRow, error)
	MarcarTicketTratado(ctx context.Context, arg MarcarTicketTratadoParams) (Tickets, error)
	MarcarTrocaPinObrigatoria(ctx context.Context, id pgtype.UUID) error
	ObterAviso(ctx context.Context, id pgtype.UUID) (Avisos, error)
	ObterFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) (ObterFotoUsuarioRow, error)
	ObterLink(ctx context.Context, id pgtype.UUID) (Links, error)
	ObterMonitor(ctx context.Context, id pgtype.UUID) (Monitores, error)
	ObterPlantao(ctx context.Context, id pgtype.UUID) (Plantoes, error)
	ObterUltimaMovimentacaoItem(ctx context.Context, itemID pgtype.UUID) (MovimentacoesEstoque, error)
	ObterUsoAssistente(ctx context.Context) (ObterUsoAssistenteRow, error)
	ObterVersaoFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Timestamptz, error)
	// Turno em andamento ou o próximo da pessoa
	ProximoPlantaoUsuario(ctx context.Context, arg ProximoPlantaoUsuarioParams) (ProximoPlantaoUsuarioRow, error)
	RegistrarEntradaTecnico(ctx context.Context, arg RegistrarEntradaTecnicoParams) (TecnicoRegistros, error)
	RegistrarSaidaTecnico(ctx context.Context, arg RegistrarSaidaTecnicoParams) (TecnicoRegistros, error)
	RegistrarUsoAssistente(ctx context.Context, neurons float64) error
	RegistrarVerificacao(ctx context.Context, arg RegistrarVerificacaoParams) error
	// Depois de trocar o alvo ou desligar: a próxima verificação decide de novo.
	ReiniciarEstadoMonitor(ctx context.Context, id pgtype.UUID) error
	// Consolidado por técnico no período (pela data de entrada). Registros ainda
	// em aberto contam como visita, mas não somam horas.
	RelatorioTecnicos(ctx context.Context, arg RelatorioTecnicosParams) ([]RelatorioTecnicosRow, error)
	RemoverFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) error
	RemoverParticipantesEvento(ctx context.Context, eventoID pgtype.UUID) error
	// Conta a tentativa ANTES de comparar o PIN, numa única instrução atômica:
	// requisições simultâneas não passam juntas pela checagem de bloqueio.
	// Sem linha retornada = usuário inexistente, inativo ou bloqueado.
	// A contagem recomeça após 15 min sem tentativas ou ao fim de um bloqueio
	// (o WHERE garante que bloqueado_ate, se preenchido, já expirou). A 5ª
	// tentativa seguida bloqueia por 5 min, 15 min, 45 min e depois 1 h.
	ReservarTentativaPin(ctx context.Context, id pgtype.UUID) (ReservarTentativaPinRow, error)
	ResumoMonitores(ctx context.Context) (ResumoMonitoresRow, error)
	SalvarFotoUsuario(ctx context.Context, arg SalvarFotoUsuarioParams) (pgtype.Timestamptz, error)
	// Tempo em queda de cada monitor dentro das últimas 24 horas
	SegundosForaUltimas24h(ctx context.Context) ([]SegundosForaUltimas24hRow, error)
	// Serializa as gravações da escala para a checagem de conflito valer
	TravarEscala(ctx context.Context) error
	VincularTicketQueda(ctx context.Context, arg VincularTicketQuedaParams) error
	ZerarTentativasFalhas(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
