// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessoes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarUltimoUsoSessao = `-- name: AtualizarUltimoUsoSessao :exec
UPDATE sessoes
SET ultimo_uso_em = $2
WHERE id = $1
`

type AtualizarUltimoUsoSessaoParams struct {
	ID          pgtype.UUID        `json:"id"`
	UltimoUsoEm pgtype.Timestamptz `json:"ultimo_uso_em"`
}

func (q *Queries) AtualizarUltimoUsoSessao(ctx context.Context, arg AtualizarUltimoUsoSessaoParams) error {
	_, err := q.db.Exec(ctx, atualizarUltimoUsoSessao, arg.ID, arg.UltimoUsoEm)
	return err
}

const buscarSessaoPorHash = `-- name: BuscarSessaoPorHash :one
SELECT 
    s.id,
    s.token_hash,
    s.usuario_id,
    s.expira_em,
    s.ultimo_uso_em,
    s.criado_em,
    u.nome AS usuario_nome,
    u.cor AS usuario_cor,
    u.papel AS usuario_papel,
    u.ativo AS usuario_ativo,
    u.tema AS usuario_tema
FROM sessoes s
JOIN usuarios u ON u.id = s.usuario_id
WHERE s.token_hash = $1 AND u.ativo = true
`

type BuscarSessaoPorHashRow struct {
	ID           pgtype.UUID        `json:"id"`
	TokenHash    string             `json:"token_hash"`
	UsuarioID    pgtype.UUID        `json:"usuario_id"`
	ExpiraEm     pgtype.Timestamptz `json:"expira_em"`
	UltimoUsoEm  pgtype.Timestamptz `json:"ultimo_uso_em"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	UsuarioNome  string             `json:"usuario_nome"`
	UsuarioCor   string             `json:"usuario_cor"`
	UsuarioPapel string             `json:"usuario_papel"`
	UsuarioAtivo bool               `json:"usuario_ativo"`
	UsuarioTema  string             `json:"usuario_tema"`
}

func (q *Queries) BuscarSessaoPorHash(ctx context.Context, tokenHash string) (BuscarSessaoPorHashRow, error) {
	row := q.db.QueryRow(ctx, buscarSessaoPorHash, tokenHash)
	var i BuscarSessaoPorHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UsuarioID,
		&i.ExpiraEm,
		&i.UltimoUsoEm,
		&i.CriadoEm,
		&i.UsuarioNome,
		&i.UsuarioCor,
		&i.UsuarioPapel,
		&i.UsuarioAtivo,
		&i.UsuarioTema,
	)
	return i, err
}

const criarSessao = `-- name: CriarSessao :one
INSERT INTO sessoes (token_hash, usuario_id, expira_em, ultimo_uso_em)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, usuario_id, expira_em, ultimo_uso_em, criado_em
`

type CriarSessaoParams struct {
	TokenHash   string             `json:"token_hash"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	ExpiraEm    pgtype.Timestamptz `json:"expira_em"`
	UltimoUsoEm pgtype.Timestamptz `json:"ultimo_uso_em"`
}

func (q *Queries) CriarSessao(ctx context.Context, arg CriarSessaoParams) (Sessoes, error) {
	row := q.db.QueryRow(ctx, criarSessao,
		arg.TokenHash,
		arg.UsuarioID,
		arg.ExpiraEm,
		arg.UltimoUsoEm,
	)
	var i Sessoes
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UsuarioID,
		&i.ExpiraEm,
		&i.UltimoUsoEm,
		&i.CriadoEm,
	)
	return i, err
}

const deletarSessaoPorHash = `-- name: DeletarSessaoPorHash :exec
DELETE FROM sessoes
WHERE token_hash = $1
`

func (q *Queries) DeletarSessaoPorHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deletarSessaoPorHash, tokenHash)
	return err
}

const deletarSessoesExpiradas = `-- name: DeletarSessoesExpiradas :exec
DELETE FROM sessoes
WHERE expira_em < now()
`

func (q *Queries) DeletarSessoesExpiradas(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletarSessoesExpiradas)
	return err
}

const deletarSessoesPorUsuario = `-- name: DeletarSessoesPorUsuario :exec
DELETE FROM sessoes
WHERE usuario_id = $1
`

func (q *Queries) DeletarSessoesPorUsuario(ctx context.Context, usuarioID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarSessoesPorUsuario, usuarioID)
	return err
}
