// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setores.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarSetor = `-- name: AtualizarSetor :one
UPDATE setores
SET nome = $2, aceita_pedidos = $3, modulos_desativados = $4
WHERE id = $1
RETURNING id, nome, aceita_pedidos, criado_em, modulos_desativados
`

type AtualizarSetorParams struct {
	ID                 pgtype.UUID `json:"id"`
	Nome               string      `json:"nome"`
	AceitaPedidos      bool        `json:"aceita_pedidos"`
	ModulosDesativados []string    `json:"modulos_desativados"`
}

func (q *Queries) AtualizarSetor(ctx context.Context, arg AtualizarSetorParams) (Setores, error) {
	row := q.db.QueryRow(ctx, atualizarSetor,
		arg.ID,
		arg.Nome,
		arg.AceitaPedidos,
		arg.ModulosDesativados,
	)
	var i Setores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.AceitaPedidos,
		&i.CriadoEm,
		&i.ModulosDesativados,
	)
	return i, err
}

const buscarSetor = `-- name: BuscarSetor :one
SELECT id, nome, aceita_pedidos, criado_em, modulos_desativados FROM setores WHERE id = $1
`

func (q *Queries) BuscarSetor(ctx context.Context, id pgtype.UUID) (Setores, error) {
	row := q.db.QueryRow(ctx, buscarSetor, id)
	var i Setores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.AceitaPedidos,
		&i.CriadoEm,
		&i.ModulosDesativados,
	)
	return i, err
}

const criarSetor = `-- name: CriarSetor :one
INSERT INTO setores (nome, aceita_pedidos, modulos_desativados)
VALUES ($1, $2, $3)
RETURNING id, nome, aceita_pedidos, criado_em, modulos_desativados
`

type CriarSetorParams struct {
	Nome               string   `json:"nome"`
	AceitaPedidos      bool     `json:"aceita_pedidos"`
	ModulosDesativados []string `json:"modulos_desativados"`
}

func (q *Queries) CriarSetor(ctx context.Context, arg CriarSetorParams) (Setores, error) {
	row := q.db.QueryRow(ctx, criarSetor, arg.Nome, arg.AceitaPedidos, arg.ModulosDesativados)
	var i Setores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.AceitaPedidos,
		&i.CriadoEm,
		&i.ModulosDesativados,
	)
	return i, err
}

const definirSetorSessao = `-- name: DefinirSetorSessao :exec
UPDATE sessoes SET setor_id = $2 WHERE id = $1
`

type DefinirSetorSessaoParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) DefinirSetorSessao(ctx context.Context, arg DefinirSetorSessaoParams) error {
	_, err := q.db.Exec(ctx, definirSetorSessao, arg.ID, arg.SetorID)
	return err
}

const deletarSetor = `-- name: DeletarSetor :execrows
DELETE FROM setores WHERE id = $1
`

func (q *Queries) DeletarSetor(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletarSetor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarEquipeSetor = `-- name: ListarEquipeSetor :many
SELECT u.id, u.nome, u.cor, f.atualizado_em AS foto_atualizada_em
FROM usuarios u
LEFT JOIN usuario_fotos f ON f.usuario_id = u.id
WHERE u.ativo AND u.setor_id = $1
ORDER BY u.nome ASC
`

type ListarEquipeSetorRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	FotoAtualizadaEm pgtype.Timestamptz `json:"foto_atualizada_em"`
}

// Operadores ativos do setor (responsável de tarefa, participantes, escala)
func (q *Queries) ListarEquipeSetor(ctx context.Context, setorID pgtype.UUID) ([]ListarEquipeSetorRow, error) {
	rows, err := q.db.Query(ctx, listarEquipeSetor, setorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEquipeSetorRow
	for rows.Next() {
		var i ListarEquipeSetorRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Cor,
			&i.FotoAtualizadaEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSetores = `-- name: ListarSetores :many
SELECT
    s.id, s.nome, s.aceita_pedidos, s.modulos_desativados, s.criado_em,
    (SELECT count(*) FROM usuarios u WHERE u.setor_id = s.id AND u.ativo) AS usuarios_ativos
FROM setores s
ORDER BY lower(s.nome)
`

type ListarSetoresRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Nome               string             `json:"nome"`
	AceitaPedidos      bool               `json:"aceita_pedidos"`
	ModulosDesativados []string           `json:"modulos_desativados"`
	CriadoEm           pgtype.Timestamptz `json:"criado_em"`
	UsuariosAtivos     int64              `json:"usuarios_ativos"`
}

func (q *Queries) ListarSetores(ctx context.Context) ([]ListarSetoresRow, error) {
	rows, err := q.db.Query(ctx, listarSetores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSetoresRow
	for rows.Next() {
		var i ListarSetoresRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.AceitaPedidos,
			&i.ModulosDesativados,
			&i.CriadoEm,
			&i.UsuariosAtivos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarSetoresPedidos = `-- name: ListarSetoresPedidos :many
SELECT id, nome, modulos_desativados FROM setores
WHERE aceita_pedidos
ORDER BY lower(nome)
`

type ListarSetoresPedidosRow struct {
	ID                 pgtype.UUID `json:"id"`
	Nome               string      `json:"nome"`
	ModulosDesativados []string    `json:"modulos_desativados"`
}

// Setores que aparecem na tela de acesso (ticket e tira-dúvidas)
func (q *Queries) ListarSetoresPedidos(ctx context.Context) ([]ListarSetoresPedidosRow, error) {
	rows, err := q.db.Query(ctx, listarSetoresPedidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarSetoresPedidosRow
	for rows.Next() {
		var i ListarSetoresPedidosRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.ModulosDesativados); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const primeiroSetor = `-- name: PrimeiroSetor :one
SELECT id, nome, aceita_pedidos, criado_em, modulos_desativados FROM setores ORDER BY criado_em, nome LIMIT 1
`

func (q *Queries) PrimeiroSetor(ctx context.Context) (Setores, error) {
	row := q.db.QueryRow(ctx, primeiroSetor)
	var i Setores
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.AceitaPedidos,
		&i.CriadoEm,
		&i.ModulosDesativados,
	)
	return i, err
}

const usuarioAtivoNoSetor = `-- name: UsuarioAtivoNoSetor :one
SELECT EXISTS (
    SELECT 1 FROM usuarios WHERE id = $1 AND setor_id = $2 AND ativo
)
`

type UsuarioAtivoNoSetorParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) UsuarioAtivoNoSetor(ctx context.Context, arg UsuarioAtivoNoSetorParams) (bool, error) {
	row := q.db.QueryRow(ctx, usuarioAtivoNoSetor, arg.ID, arg.SetorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
