// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tarefas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarStatusTarefa = `-- name: AtualizarStatusTarefa :one
UPDATE tarefas
SET status = $1::varchar,
    concluida_em = CASE 
        WHEN $1::varchar = 'concluida' THEN now() 
        ELSE NULL 
    END,
    atualizado_em = now()
WHERE id = $2::uuid
RETURNING id, titulo, descricao, status, prioridade, prazo, criado_por, responsavel_id, concluida_em, criado_em, atualizado_em
`

type AtualizarStatusTarefaParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) AtualizarStatusTarefa(ctx context.Context, arg AtualizarStatusTarefaParams) (Tarefas, error) {
	row := q.db.QueryRow(ctx, atualizarStatusTarefa, arg.Status, arg.ID)
	var i Tarefas
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.Status,
		&i.Prioridade,
		&i.Prazo,
		&i.CriadoPor,
		&i.ResponsavelID,
		&i.ConcluidaEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const atualizarTarefa = `-- name: AtualizarTarefa :one
UPDATE tarefas
SET titulo = $2, descricao = $3, prioridade = $4, prazo = $5, responsavel_id = $6, atualizado_em = now()
WHERE id = $1
RETURNING id, titulo, descricao, status, prioridade, prazo, criado_por, responsavel_id, concluida_em, criado_em, atualizado_em
`

type AtualizarTarefaParams struct {
	ID            pgtype.UUID        `json:"id"`
	Titulo        string             `json:"titulo"`
	Descricao     string             `json:"descricao"`
	Prioridade    string             `json:"prioridade"`
	Prazo         pgtype.Timestamptz `json:"prazo"`
	ResponsavelID pgtype.UUID        `json:"responsavel_id"`
}

func (q *Queries) AtualizarTarefa(ctx context.Context, arg AtualizarTarefaParams) (Tarefas, error) {
	row := q.db.QueryRow(ctx, atualizarTarefa,
		arg.ID,
		arg.Titulo,
		arg.Descricao,
		arg.Prioridade,
		arg.Prazo,
		arg.ResponsavelID,
	)
	var i Tarefas
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.Status,
		&i.Prioridade,
		&i.Prazo,
		&i.CriadoPor,
		&i.ResponsavelID,
		&i.ConcluidaEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarComentarioPorID = `-- name: BuscarComentarioPorID :one
SELECT id, tarefa_id, usuario_id, conteudo, criado_em
FROM tarefa_comentarios
WHERE id = $1
`

func (q *Queries) BuscarComentarioPorID(ctx context.Context, id pgtype.UUID) (TarefaComentarios, error) {
	row := q.db.QueryRow(ctx, buscarComentarioPorID, id)
	var i TarefaComentarios
	err := row.Scan(
		&i.ID,
		&i.TarefaID,
		&i.UsuarioID,
		&i.Conteudo,
		&i.CriadoEm,
	)
	return i, err
}

const buscarTarefaPorID = `-- name: BuscarTarefaPorID :one
SELECT 
    t.id, t.titulo, t.descricao, t.status, t.prioridade, t.prazo, 
    t.criado_por, t.responsavel_id, t.concluida_em, t.criado_em, t.atualizado_em,
    uc.nome AS criador_nome, uc.cor AS criador_cor,
    ur.nome AS responsavel_nome, ur.cor AS responsavel_cor
FROM tarefas t
JOIN usuarios uc ON uc.id = t.criado_por
LEFT JOIN usuarios ur ON ur.id = t.responsavel_id
WHERE t.id = $1
`

type BuscarTarefaPorIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	Titulo          string             `json:"titulo"`
	Descricao       string             `json:"descricao"`
	Status          string             `json:"status"`
	Prioridade      string             `json:"prioridade"`
	Prazo           pgtype.Timestamptz `json:"prazo"`
	CriadoPor       pgtype.UUID        `json:"criado_por"`
	ResponsavelID   pgtype.UUID        `json:"responsavel_id"`
	ConcluidaEm     pgtype.Timestamptz `json:"concluida_em"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
	CriadorNome     string             `json:"criador_nome"`
	CriadorCor      string             `json:"criador_cor"`
	ResponsavelNome pgtype.Text        `json:"responsavel_nome"`
	ResponsavelCor  pgtype.Text        `json:"responsavel_cor"`
}

func (q *Queries) BuscarTarefaPorID(ctx context.Context, id pgtype.UUID) (BuscarTarefaPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarTarefaPorID, id)
	var i BuscarTarefaPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.Status,
		&i.Prioridade,
		&i.Prazo,
		&i.CriadoPor,
		&i.ResponsavelID,
		&i.ConcluidaEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.CriadorNome,
		&i.CriadorCor,
		&i.ResponsavelNome,
		&i.ResponsavelCor,
	)
	return i, err
}

const criarComentarioTarefa = `-- name: CriarComentarioTarefa :one
INSERT INTO tarefa_comentarios (tarefa_id, usuario_id, conteudo)
VALUES ($1, $2, $3)
RETURNING id, tarefa_id, usuario_id, conteudo, criado_em
`

type CriarComentarioTarefaParams struct {
	TarefaID  pgtype.UUID `json:"tarefa_id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Conteudo  string      `json:"conteudo"`
}

func (q *Queries) CriarComentarioTarefa(ctx context.Context, arg CriarComentarioTarefaParams) (TarefaComentarios, error) {
	row := q.db.QueryRow(ctx, criarComentarioTarefa, arg.TarefaID, arg.UsuarioID, arg.Conteudo)
	var i TarefaComentarios
	err := row.Scan(
		&i.ID,
		&i.TarefaID,
		&i.UsuarioID,
		&i.Conteudo,
		&i.CriadoEm,
	)
	return i, err
}

const criarTarefa = `-- name: CriarTarefa :one
INSERT INTO tarefas (titulo, descricao, prioridade, prazo, criado_por, responsavel_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, titulo, descricao, status, prioridade, prazo, criado_por, responsavel_id, concluida_em, criado_em, atualizado_em
`

type CriarTarefaParams struct {
	Titulo        string             `json:"titulo"`
	Descricao     string             `json:"descricao"`
	Prioridade    string             `json:"prioridade"`
	Prazo         pgtype.Timestamptz `json:"prazo"`
	CriadoPor     pgtype.UUID        `json:"criado_por"`
	ResponsavelID pgtype.UUID        `json:"responsavel_id"`
}

func (q *Queries) CriarTarefa(ctx context.Context, arg CriarTarefaParams) (Tarefas, error) {
	row := q.db.QueryRow(ctx, criarTarefa,
		arg.Titulo,
		arg.Descricao,
		arg.Prioridade,
		arg.Prazo,
		arg.CriadoPor,
		arg.ResponsavelID,
	)
	var i Tarefas
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.Status,
		&i.Prioridade,
		&i.Prazo,
		&i.CriadoPor,
		&i.ResponsavelID,
		&i.ConcluidaEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deletarComentarioTarefa = `-- name: DeletarComentarioTarefa :exec
DELETE FROM tarefa_comentarios
WHERE id = $1
`

func (q *Queries) DeletarComentarioTarefa(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarComentarioTarefa, id)
	return err
}

const deletarTarefa = `-- name: DeletarTarefa :exec
DELETE FROM tarefas
WHERE id = $1
`

func (q *Queries) DeletarTarefa(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarTarefa, id)
	return err
}

const listarComentariosTarefa = `-- name: ListarComentariosTarefa :many
SELECT 
    c.id, c.tarefa_id, c.usuario_id, c.conteudo, c.criado_em,
    u.nome AS usuario_nome, u.cor AS usuario_cor
FROM tarefa_comentarios c
JOIN usuarios u ON u.id = c.usuario_id
WHERE c.tarefa_id = $1
ORDER BY c.criado_em ASC
`

type ListarComentariosTarefaRow struct {
	ID          pgtype.UUID        `json:"id"`
	TarefaID    pgtype.UUID        `json:"tarefa_id"`
	UsuarioID   pgtype.UUID        `json:"usuario_id"`
	Conteudo    string             `json:"conteudo"`
	CriadoEm    pgtype.Timestamptz `json:"criado_em"`
	UsuarioNome string             `json:"usuario_nome"`
	UsuarioCor  string             `json:"usuario_cor"`
}

func (q *Queries) ListarComentariosTarefa(ctx context.Context, tarefaID pgtype.UUID) ([]ListarComentariosTarefaRow, error) {
	rows, err := q.db.Query(ctx, listarComentariosTarefa, tarefaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarComentariosTarefaRow
	for rows.Next() {
		var i ListarComentariosTarefaRow
		if err := rows.Scan(
			&i.ID,
			&i.TarefaID,
			&i.UsuarioID,
			&i.Conteudo,
			&i.CriadoEm,
			&i.UsuarioNome,
			&i.UsuarioCor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTarefas = `-- name: ListarTarefas :many
SELECT 
    t.id, t.titulo, t.descricao, t.status, t.prioridade, t.prazo, 
    t.criado_por, t.responsavel_id, t.concluida_em, t.criado_em, t.atualizado_em,
    uc.nome AS criador_nome, uc.cor AS criador_cor,
    ur.nome AS responsavel_nome, ur.cor AS responsavel_cor
FROM tarefas t
JOIN usuarios uc ON uc.id = t.criado_por
LEFT JOIN usuarios ur ON ur.id = t.responsavel_id
WHERE 
    ($1::uuid IS NULL OR t.responsavel_id = $1)
    AND ($2::uuid IS NULL OR t.criado_por = $2)
    AND ($3::text IS NULL OR t.status = $3)
ORDER BY 
    CASE WHEN t.status = 'concluida' THEN 1 ELSE 0 END ASC,
    CASE WHEN t.prazo IS NOT NULL AND t.prazo < now() AND t.status != 'concluida' THEN 0 ELSE 1 END ASC,
    t.prazo ASC NULLS LAST,
    CASE t.prioridade 
        WHEN 'alta' THEN 1 
        WHEN 'media' THEN 2 
        WHEN 'baixa' THEN 3 
        ELSE 4 
    END ASC,
    t.criado_em DESC
`

type ListarTarefasParams struct {
	ResponsavelID pgtype.UUID `json:"responsavel_id"`
	CriadoPor     pgtype.UUID `json:"criado_por"`
	Status        pgtype.Text `json:"status"`
}

type ListarTarefasRow struct {
	ID              pgtype.UUID        `json:"id"`
	Titulo          string             `json:"titulo"`
	Descricao       string             `json:"descricao"`
	Status          string             `json:"status"`
	Prioridade      string             `json:"prioridade"`
	Prazo           pgtype.Timestamptz `json:"prazo"`
	CriadoPor       pgtype.UUID        `json:"criado_por"`
	ResponsavelID   pgtype.UUID        `json:"responsavel_id"`
	ConcluidaEm     pgtype.Timestamptz `json:"concluida_em"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
	CriadorNome     string             `json:"criador_nome"`
	CriadorCor      string             `json:"criador_cor"`
	ResponsavelNome pgtype.Text        `json:"responsavel_nome"`
	ResponsavelCor  pgtype.Text        `json:"responsavel_cor"`
}

func (q *Queries) ListarTarefas(ctx context.Context, arg ListarTarefasParams) ([]ListarTarefasRow, error) {
	rows, err := q.db.Query(ctx, listarTarefas, arg.ResponsavelID, arg.CriadoPor, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTarefasRow
	for rows.Next() {
		var i ListarTarefasRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.Status,
			&i.Prioridade,
			&i.Prazo,
			&i.CriadoPor,
			&i.ResponsavelID,
			&i.ConcluidaEm,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.CriadorNome,
			&i.CriadorCor,
			&i.ResponsavelNome,
			&i.ResponsavelCor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTarefasPendentesUsuario = `-- name: ListarTarefasPendentesUsuario :many
SELECT 
    t.id, t.titulo, t.descricao, t.status, t.prioridade, t.prazo, 
    t.criado_por, t.responsavel_id, t.concluida_em, t.criado_em, t.atualizado_em,
    uc.nome AS criador_nome, uc.cor AS criador_cor
FROM tarefas t
JOIN usuarios uc ON uc.id = t.criado_por
WHERE t.responsavel_id = $1 AND t.status != 'concluida'
ORDER BY 
    CASE WHEN t.prazo IS NOT NULL AND t.prazo < now() THEN 0 ELSE 1 END ASC,
    t.prazo ASC NULLS LAST,
    CASE t.prioridade 
        WHEN 'alta' THEN 1 
        WHEN 'media' THEN 2 
        WHEN 'baixa' THEN 3 
        ELSE 4 
    END ASC
`

type ListarTarefasPendentesUsuarioRow struct {
	ID            pgtype.UUID        `json:"id"`
	Titulo        string             `json:"titulo"`
	Descricao     string             `json:"descricao"`
	Status        string             `json:"status"`
	Prioridade    string             `json:"prioridade"`
	Prazo         pgtype.Timestamptz `json:"prazo"`
	CriadoPor     pgtype.UUID        `json:"criado_por"`
	ResponsavelID pgtype.UUID        `json:"responsavel_id"`
	ConcluidaEm   pgtype.Timestamptz `json:"concluida_em"`
	CriadoEm      pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm  pgtype.Timestamptz `json:"atualizado_em"`
	CriadorNome   string             `json:"criador_nome"`
	CriadorCor    string             `json:"criador_cor"`
}

func (q *Queries) ListarTarefasPendentesUsuario(ctx context.Context, responsavelID pgtype.UUID) ([]ListarTarefasPendentesUsuarioRow, error) {
	rows, err := q.db.Query(ctx, listarTarefasPendentesUsuario, responsavelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTarefasPendentesUsuarioRow
	for rows.Next() {
		var i ListarTarefasPendentesUsuarioRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.Status,
			&i.Prioridade,
			&i.Prazo,
			&i.CriadoPor,
			&i.ResponsavelID,
			&i.ConcluidaEm,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.CriadorNome,
			&i.CriadorCor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
