// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tecnicos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarAtividadesRegistro = `-- name: AtualizarAtividadesRegistro :one
UPDATE tecnico_registros
SET atividades = $2, atualizado_em = now()
WHERE tecnico_registros.id = $1
  AND tecnico_registros.tecnico_id IN (SELECT t.id FROM tecnicos t WHERE t.setor_id = $3)
RETURNING id, tecnico_id, entrada, saida, observacao, entrada_registrada_por, saida_registrada_por, criado_em, atualizado_em, atividades
`

type AtualizarAtividadesRegistroParams struct {
	ID         pgtype.UUID `json:"id"`
	Atividades string      `json:"atividades"`
	SetorID    pgtype.UUID `json:"setor_id"`
}

func (q *Queries) AtualizarAtividadesRegistro(ctx context.Context, arg AtualizarAtividadesRegistroParams) (TecnicoRegistros, error) {
	row := q.db.QueryRow(ctx, atualizarAtividadesRegistro, arg.ID, arg.Atividades, arg.SetorID)
	var i TecnicoRegistros
	err := row.Scan(
		&i.ID,
		&i.TecnicoID,
		&i.Entrada,
		&i.Saida,
		&i.Observacao,
		&i.EntradaRegistradaPor,
		&i.SaidaRegistradaPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Atividades,
	)
	return i, err
}

const atualizarRegistroTecnico = `-- name: AtualizarRegistroTecnico :one
UPDATE tecnico_registros
SET entrada = $2, saida = $3, observacao = $4, atualizado_em = now()
WHERE tecnico_registros.id = $1
  AND tecnico_registros.tecnico_id IN (SELECT t.id FROM tecnicos t WHERE t.setor_id = $5)
RETURNING id, tecnico_id, entrada, saida, observacao, entrada_registrada_por, saida_registrada_por, criado_em, atualizado_em, atividades
`

type AtualizarRegistroTecnicoParams struct {
	ID         pgtype.UUID        `json:"id"`
	Entrada    pgtype.Timestamptz `json:"entrada"`
	Saida      pgtype.Timestamptz `json:"saida"`
	Observacao string             `json:"observacao"`
	SetorID    pgtype.UUID        `json:"setor_id"`
}

func (q *Queries) AtualizarRegistroTecnico(ctx context.Context, arg AtualizarRegistroTecnicoParams) (TecnicoRegistros, error) {
	row := q.db.QueryRow(ctx, atualizarRegistroTecnico,
		arg.ID,
		arg.Entrada,
		arg.Saida,
		arg.Observacao,
		arg.SetorID,
	)
	var i TecnicoRegistros
	err := row.Scan(
		&i.ID,
		&i.TecnicoID,
		&i.Entrada,
		&i.Saida,
		&i.Observacao,
		&i.EntradaRegistradaPor,
		&i.SaidaRegistradaPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Atividades,
	)
	return i, err
}

const atualizarTecnico = `-- name: AtualizarTecnico :one
UPDATE tecnicos
SET nome = $2, empresa = $3, ativo = $4
WHERE id = $1 AND setor_id = $5
RETURNING id, nome, empresa, ativo, criado_em, setor_id
`

type AtualizarTecnicoParams struct {
	ID      pgtype.UUID `json:"id"`
	Nome    string      `json:"nome"`
	Empresa string      `json:"empresa"`
	Ativo   bool        `json:"ativo"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) AtualizarTecnico(ctx context.Context, arg AtualizarTecnicoParams) (Tecnicos, error) {
	row := q.db.QueryRow(ctx, atualizarTecnico,
		arg.ID,
		arg.Nome,
		arg.Empresa,
		arg.Ativo,
		arg.SetorID,
	)
	var i Tecnicos
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Empresa,
		&i.Ativo,
		&i.CriadoEm,
		&i.SetorID,
	)
	return i, err
}

const buscarRegistroTecnicoPorID = `-- name: BuscarRegistroTecnicoPorID :one
SELECT r.id, r.tecnico_id, r.entrada, r.saida, r.observacao, r.entrada_registrada_por, r.saida_registrada_por, r.criado_em, r.atualizado_em, r.atividades FROM tecnico_registros r
JOIN tecnicos t ON t.id = r.tecnico_id
WHERE r.id = $1 AND t.setor_id = $2
`

type BuscarRegistroTecnicoPorIDParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) BuscarRegistroTecnicoPorID(ctx context.Context, arg BuscarRegistroTecnicoPorIDParams) (TecnicoRegistros, error) {
	row := q.db.QueryRow(ctx, buscarRegistroTecnicoPorID, arg.ID, arg.SetorID)
	var i TecnicoRegistros
	err := row.Scan(
		&i.ID,
		&i.TecnicoID,
		&i.Entrada,
		&i.Saida,
		&i.Observacao,
		&i.EntradaRegistradaPor,
		&i.SaidaRegistradaPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Atividades,
	)
	return i, err
}

const buscarTecnicoPorID = `-- name: BuscarTecnicoPorID :one
SELECT id, nome, empresa, ativo, criado_em
FROM tecnicos
WHERE id = $1 AND setor_id = $2
`

type BuscarTecnicoPorIDParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

type BuscarTecnicoPorIDRow struct {
	ID       pgtype.UUID        `json:"id"`
	Nome     string             `json:"nome"`
	Empresa  string             `json:"empresa"`
	Ativo    bool               `json:"ativo"`
	CriadoEm pgtype.Timestamptz `json:"criado_em"`
}

func (q *Queries) BuscarTecnicoPorID(ctx context.Context, arg BuscarTecnicoPorIDParams) (BuscarTecnicoPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarTecnicoPorID, arg.ID, arg.SetorID)
	var i BuscarTecnicoPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Empresa,
		&i.Ativo,
		&i.CriadoEm,
	)
	return i, err
}

const contarRegistrosTecnicos = `-- name: ContarRegistrosTecnicos :one
SELECT count(*)
FROM tecnico_registros r
JOIN tecnicos t ON t.id = r.tecnico_id
WHERE t.setor_id = $1
    AND ($2::uuid IS NULL OR r.tecnico_id = $2)
    AND ($3::timestamptz IS NULL OR r.entrada >= $3)
    AND ($4::timestamptz IS NULL OR r.entrada < $4)
`

type ContarRegistrosTecnicosParams struct {
	SetorID    pgtype.UUID        `json:"setor_id"`
	TecnicoID  pgtype.UUID        `json:"tecnico_id"`
	DataInicio pgtype.Timestamptz `json:"data_inicio"`
	DataFim    pgtype.Timestamptz `json:"data_fim"`
}

func (q *Queries) ContarRegistrosTecnicos(ctx context.Context, arg ContarRegistrosTecnicosParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarRegistrosTecnicos,
		arg.SetorID,
		arg.TecnicoID,
		arg.DataInicio,
		arg.DataFim,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarTecnico = `-- name: CriarTecnico :one
INSERT INTO tecnicos (nome, empresa, setor_id)
VALUES ($1, $2, $3)
RETURNING id, nome, empresa, ativo, criado_em, setor_id
`

type CriarTecnicoParams struct {
	Nome    string      `json:"nome"`
	Empresa string      `json:"empresa"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) CriarTecnico(ctx context.Context, arg CriarTecnicoParams) (Tecnicos, error) {
	row := q.db.QueryRow(ctx, criarTecnico, arg.Nome, arg.Empresa, arg.SetorID)
	var i Tecnicos
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Empresa,
		&i.Ativo,
		&i.CriadoEm,
		&i.SetorID,
	)
	return i, err
}

const deletarRegistroTecnico = `-- name: DeletarRegistroTecnico :exec
DELETE FROM tecnico_registros WHERE id = $1
`

func (q *Queries) DeletarRegistroTecnico(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletarRegistroTecnico, id)
	return err
}

const listarRegistrosTecnicos = `-- name: ListarRegistrosTecnicos :many
SELECT
    r.id, r.tecnico_id, r.entrada, r.saida, r.observacao, r.atividades, r.atualizado_em,
    t.nome AS tecnico_nome, t.empresa AS tecnico_empresa,
    ue.nome AS entrada_registrada_por_nome,
    us.nome AS saida_registrada_por_nome
FROM tecnico_registros r
JOIN tecnicos t ON t.id = r.tecnico_id
JOIN usuarios ue ON ue.id = r.entrada_registrada_por
LEFT JOIN usuarios us ON us.id = r.saida_registrada_por
WHERE t.setor_id = $3
    AND ($4::uuid IS NULL OR r.tecnico_id = $4)
    AND ($5::timestamptz IS NULL OR r.entrada >= $5)
    AND ($6::timestamptz IS NULL OR r.entrada < $6)
ORDER BY r.entrada DESC
LIMIT $1 OFFSET $2
`

type ListarRegistrosTecnicosParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	SetorID    pgtype.UUID        `json:"setor_id"`
	TecnicoID  pgtype.UUID        `json:"tecnico_id"`
	DataInicio pgtype.Timestamptz `json:"data_inicio"`
	DataFim    pgtype.Timestamptz `json:"data_fim"`
}

type ListarRegistrosTecnicosRow struct {
	ID                       pgtype.UUID        `json:"id"`
	TecnicoID                pgtype.UUID        `json:"tecnico_id"`
	Entrada                  pgtype.Timestamptz `json:"entrada"`
	Saida                    pgtype.Timestamptz `json:"saida"`
	Observacao               string             `json:"observacao"`
	Atividades               string             `json:"atividades"`
	AtualizadoEm             pgtype.Timestamptz `json:"atualizado_em"`
	TecnicoNome              string             `json:"tecnico_nome"`
	TecnicoEmpresa           string             `json:"tecnico_empresa"`
	EntradaRegistradaPorNome string             `json:"entrada_registrada_por_nome"`
	SaidaRegistradaPorNome   pgtype.Text        `json:"saida_registrada_por_nome"`
}

func (q *Queries) ListarRegistrosTecnicos(ctx context.Context, arg ListarRegistrosTecnicosParams) ([]ListarRegistrosTecnicosRow, error) {
	rows, err := q.db.Query(ctx, listarRegistrosTecnicos,
		arg.Limit,
		arg.Offset,
		arg.SetorID,
		arg.TecnicoID,
		arg.DataInicio,
		arg.DataFim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarRegistrosTecnicosRow
	for rows.Next() {
		var i ListarRegistrosTecnicosRow
		if err := rows.Scan(
			&i.ID,
			&i.TecnicoID,
			&i.Entrada,
			&i.Saida,
			&i.Observacao,
			&i.Atividades,
			&i.AtualizadoEm,
			&i.TecnicoNome,
			&i.TecnicoEmpresa,
			&i.EntradaRegistradaPorNome,
			&i.SaidaRegistradaPorNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarTecnicos = `-- name: ListarTecnicos :many
SELECT
    t.id, t.nome, t.empresa, t.ativo, t.criado_em,
    r.id AS registro_aberto_id,
    r.entrada AS entrada_aberta,
    r.atividades AS atividades_abertas
FROM tecnicos t
LEFT JOIN tecnico_registros r ON r.tecnico_id = t.id AND r.saida IS NULL
WHERE t.setor_id = $1
  AND ($2::boolean IS NULL OR t.ativo = $2)
ORDER BY t.nome ASC
`

type ListarTecnicosParams struct {
	SetorID pgtype.UUID `json:"setor_id"`
	Ativo   pgtype.Bool `json:"ativo"`
}

type ListarTecnicosRow struct {
	ID                pgtype.UUID        `json:"id"`
	Nome              string             `json:"nome"`
	Empresa           string             `json:"empresa"`
	Ativo             bool               `json:"ativo"`
	CriadoEm          pgtype.Timestamptz `json:"criado_em"`
	RegistroAbertoID  pgtype.UUID        `json:"registro_aberto_id"`
	EntradaAberta     pgtype.Timestamptz `json:"entrada_aberta"`
	AtividadesAbertas pgtype.Text        `json:"atividades_abertas"`
}

func (q *Queries) ListarTecnicos(ctx context.Context, arg ListarTecnicosParams) ([]ListarTecnicosRow, error) {
	rows, err := q.db.Query(ctx, listarTecnicos, arg.SetorID, arg.Ativo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTecnicosRow
	for rows.Next() {
		var i ListarTecnicosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Empresa,
			&i.Ativo,
			&i.CriadoEm,
			&i.RegistroAbertoID,
			&i.EntradaAberta,
			&i.AtividadesAbertas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarEntradaTecnico = `-- name: RegistrarEntradaTecnico :one
INSERT INTO tecnico_registros (tecnico_id, entrada, observacao, entrada_registrada_por)
VALUES ($1, $2, $3, $4)
RETURNING id, tecnico_id, entrada, saida, observacao, entrada_registrada_por, saida_registrada_por, criado_em, atualizado_em, atividades
`

type RegistrarEntradaTecnicoParams struct {
	TecnicoID            pgtype.UUID        `json:"tecnico_id"`
	Entrada              pgtype.Timestamptz `json:"entrada"`
	Observacao           string             `json:"observacao"`
	EntradaRegistradaPor pgtype.UUID        `json:"entrada_registrada_por"`
}

func (q *Queries) RegistrarEntradaTecnico(ctx context.Context, arg RegistrarEntradaTecnicoParams) (TecnicoRegistros, error) {
	row := q.db.QueryRow(ctx, registrarEntradaTecnico,
		arg.TecnicoID,
		arg.Entrada,
		arg.Observacao,
		arg.EntradaRegistradaPor,
	)
	var i TecnicoRegistros
	err := row.Scan(
		&i.ID,
		&i.TecnicoID,
		&i.Entrada,
		&i.Saida,
		&i.Observacao,
		&i.EntradaRegistradaPor,
		&i.SaidaRegistradaPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Atividades,
	)
	return i, err
}

const registrarSaidaTecnico = `-- name: RegistrarSaidaTecnico :one
UPDATE tecnico_registros
SET saida = $2,
    saida_registrada_por = $3,
    observacao = CASE WHEN $4::text = '' THEN observacao
                      WHEN observacao = '' THEN $4::text
                      ELSE observacao || E'\n' || $4::text END,
    -- A tela de saída já vem com o texto anotado no dia: o enviado substitui
    atividades = CASE WHEN $5::text = '' THEN atividades
                      ELSE $5::text END,
    atualizado_em = now()
WHERE tecnico_id = $1 AND saida IS NULL
  AND tecnico_id IN (SELECT t.id FROM tecnicos t WHERE t.setor_id = $6)
RETURNING id, tecnico_id, entrada, saida, observacao, entrada_registrada_por, saida_registrada_por, criado_em, atualizado_em, atividades
`

type RegistrarSaidaTecnicoParams struct {
	TecnicoID          pgtype.UUID        `json:"tecnico_id"`
	Saida              pgtype.Timestamptz `json:"saida"`
	SaidaRegistradaPor pgtype.UUID        `json:"saida_registrada_por"`
	Observacao         string             `json:"observacao"`
	Atividades         string             `json:"atividades"`
	SetorID            pgtype.UUID        `json:"setor_id"`
}

func (q *Queries) RegistrarSaidaTecnico(ctx context.Context, arg RegistrarSaidaTecnicoParams) (TecnicoRegistros, error) {
	row := q.db.QueryRow(ctx, registrarSaidaTecnico,
		arg.TecnicoID,
		arg.Saida,
		arg.SaidaRegistradaPor,
		arg.Observacao,
		arg.Atividades,
		arg.SetorID,
	)
	var i TecnicoRegistros
	err := row.Scan(
		&i.ID,
		&i.TecnicoID,
		&i.Entrada,
		&i.Saida,
		&i.Observacao,
		&i.EntradaRegistradaPor,
		&i.SaidaRegistradaPor,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Atividades,
	)
	return i, err
}

const relatorioTecnicos = `-- name: RelatorioTecnicos :many
SELECT
    t.id AS tecnico_id,
    t.nome AS tecnico_nome,
    t.empresa AS tecnico_empresa,
    count(r.id)::bigint AS total_registros,
    count(r.id) FILTER (WHERE r.saida IS NULL)::bigint AS registros_abertos,
    count(DISTINCT (r.entrada AT TIME ZONE 'America/Sao_Paulo')::date)::bigint AS dias_presentes,
    COALESCE(sum(EXTRACT(EPOCH FROM (r.saida - r.entrada))) FILTER (WHERE r.saida IS NOT NULL), 0)::bigint AS segundos_totais,
    min(r.entrada)::timestamptz AS primeira_entrada,
    max(COALESCE(r.saida, r.entrada))::timestamptz AS ultima_marcacao
FROM tecnicos t
JOIN tecnico_registros r ON r.tecnico_id = t.id
WHERE t.setor_id = $1
    AND ($2::uuid IS NULL OR r.tecnico_id = $2)
    AND ($3::timestamptz IS NULL OR r.entrada >= $3)
    AND ($4::timestamptz IS NULL OR r.entrada < $4)
GROUP BY t.id, t.nome, t.empresa
ORDER BY t.nome ASC
`

type RelatorioTecnicosParams struct {
	SetorID    pgtype.UUID        `json:"setor_id"`
	TecnicoID  pgtype.UUID        `json:"tecnico_id"`
	DataInicio pgtype.Timestamptz `json:"data_inicio"`
	DataFim    pgtype.Timestamptz `json:"data_fim"`
}

type RelatorioTecnicosRow struct {
	TecnicoID        pgtype.UUID        `json:"tecnico_id"`
	TecnicoNome      string             `json:"tecnico_nome"`
	TecnicoEmpresa   string             `json:"tecnico_empresa"`
	TotalRegistros   int64              `json:"total_registros"`
	RegistrosAbertos int64              `json:"registros_abertos"`
	DiasPresentes    int64              `json:"dias_presentes"`
	SegundosTotais   int64              `json:"segundos_totais"`
	PrimeiraEntrada  pgtype.Timestamptz `json:"primeira_entrada"`
	UltimaMarcacao   pgtype.Timestamptz `json:"ultima_marcacao"`
}

// Consolidado por técnico no período (pela data de entrada). Registros ainda
// em aberto contam como visita, mas não somam horas.
func (q *Queries) RelatorioTecnicos(ctx context.Context, arg RelatorioTecnicosParams) ([]RelatorioTecnicosRow, error) {
	rows, err := q.db.Query(ctx, relatorioTecnicos,
		arg.SetorID,
		arg.TecnicoID,
		arg.DataInicio,
		arg.DataFim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelatorioTecnicosRow
	for rows.Next() {
		var i RelatorioTecnicosRow
		if err := rows.Scan(
			&i.TecnicoID,
			&i.TecnicoNome,
			&i.TecnicoEmpresa,
			&i.TotalRegistros,
			&i.RegistrosAbertos,
			&i.DiasPresentes,
			&i.SegundosTotais,
			&i.PrimeiraEntrada,
			&i.UltimaMarcacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
