// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telas_tv.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarTelaTVPorHash = `-- name: BuscarTelaTVPorHash :one
SELECT t.id, t.nome, t.chave_hash, t.criado_por, t.criado_em, t.ultimo_acesso_em, t.ultimo_ip, t.setor_id, s.nome AS setor_nome, s.modulos_desativados AS setor_modulos_desativados
FROM telas_tv t
JOIN setores s ON s.id = t.setor_id
WHERE t.chave_hash = $1
`

type BuscarTelaTVPorHashRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Nome                    string             `json:"nome"`
	ChaveHash               string             `json:"chave_hash"`
	CriadoPor               pgtype.UUID        `json:"criado_por"`
	CriadoEm                pgtype.Timestamptz `json:"criado_em"`
	UltimoAcessoEm          pgtype.Timestamptz `json:"ultimo_acesso_em"`
	UltimoIp                string             `json:"ultimo_ip"`
	SetorID                 pgtype.UUID        `json:"setor_id"`
	SetorNome               string             `json:"setor_nome"`
	SetorModulosDesativados []string           `json:"setor_modulos_desativados"`
}

func (q *Queries) BuscarTelaTVPorHash(ctx context.Context, chaveHash string) (BuscarTelaTVPorHashRow, error) {
	row := q.db.QueryRow(ctx, buscarTelaTVPorHash, chaveHash)
	var i BuscarTelaTVPorHashRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.ChaveHash,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.UltimoAcessoEm,
		&i.UltimoIp,
		&i.SetorID,
		&i.SetorNome,
		&i.SetorModulosDesativados,
	)
	return i, err
}

const criarTelaTV = `-- name: CriarTelaTV :one
INSERT INTO telas_tv (nome, chave_hash, criado_por, setor_id)
VALUES ($1, $2, $3, $4)
RETURNING id, nome, chave_hash, criado_por, criado_em, ultimo_acesso_em, ultimo_ip, setor_id
`

type CriarTelaTVParams struct {
	Nome      string      `json:"nome"`
	ChaveHash string      `json:"chave_hash"`
	CriadoPor pgtype.UUID `json:"criado_por"`
	SetorID   pgtype.UUID `json:"setor_id"`
}

func (q *Queries) CriarTelaTV(ctx context.Context, arg CriarTelaTVParams) (TelasTv, error) {
	row := q.db.QueryRow(ctx, criarTelaTV,
		arg.Nome,
		arg.ChaveHash,
		arg.CriadoPor,
		arg.SetorID,
	)
	var i TelasTv
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.ChaveHash,
		&i.CriadoPor,
		&i.CriadoEm,
		&i.UltimoAcessoEm,
		&i.UltimoIp,
		&i.SetorID,
	)
	return i, err
}

const deletarTelaTV = `-- name: DeletarTelaTV :execrows
DELETE FROM telas_tv WHERE id = $1 AND setor_id = $2
`

type DeletarTelaTVParams struct {
	ID      pgtype.UUID `json:"id"`
	SetorID pgtype.UUID `json:"setor_id"`
}

func (q *Queries) DeletarTelaTV(ctx context.Context, arg DeletarTelaTVParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletarTelaTV, arg.ID, arg.SetorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listarTelasTV = `-- name: ListarTelasTV :many
SELECT t.id, t.nome, t.criado_em, t.ultimo_acesso_em, t.ultimo_ip, u.nome AS criador_nome
FROM telas_tv t
JOIN usuarios u ON u.id = t.criado_por
WHERE t.setor_id = $1
ORDER BY lower(t.nome)
`

type ListarTelasTVRow struct {
	ID             pgtype.UUID        `json:"id"`
	Nome           string             `json:"nome"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	UltimoAcessoEm pgtype.Timestamptz `json:"ultimo_acesso_em"`
	UltimoIp       string             `json:"ultimo_ip"`
	CriadorNome    string             `json:"criador_nome"`
}

func (q *Queries) ListarTelasTV(ctx context.Context, setorID pgtype.UUID) ([]ListarTelasTVRow, error) {
	rows, err := q.db.Query(ctx, listarTelasTV, setorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTelasTVRow
	for rows.Next() {
		var i ListarTelasTVRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.CriadoEm,
			&i.UltimoAcessoEm,
			&i.UltimoIp,
			&i.CriadorNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registrarAcessoTelaTV = `-- name: RegistrarAcessoTelaTV :exec
UPDATE telas_tv
SET ultimo_acesso_em = now(), ultimo_ip = $2
WHERE id = $1
  AND (ultimo_acesso_em IS NULL OR ultimo_acesso_em < now() - interval '1 minute' OR ultimo_ip <> $2)
`

type RegistrarAcessoTelaTVParams struct {
	ID       pgtype.UUID `json:"id"`
	UltimoIp string      `json:"ultimo_ip"`
}

// Grava no máximo uma vez por minuto (a TV consulta a cada poucos segundos)
func (q *Queries) RegistrarAcessoTelaTV(ctx context.Context, arg RegistrarAcessoTelaTVParams) error {
	_, err := q.db.Exec(ctx, registrarAcessoTelaTV, arg.ID, arg.UltimoIp)
	return err
}
