// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bloquearTicket = `-- name: BloquearTicket :one
SELECT id, numero, solicitante_nome, titulo, descricao, prioridade, status, tarefa_id, tratado_por, tratado_em, origem_ip, criado_em FROM tickets WHERE id = $1 FOR UPDATE
`

func (q *Queries) BloquearTicket(ctx context.Context, id pgtype.UUID) (Tickets, error) {
	row := q.db.QueryRow(ctx, bloquearTicket, id)
	var i Tickets
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.SolicitanteNome,
		&i.Titulo,
		&i.Descricao,
		&i.Prioridade,
		&i.Status,
		&i.TarefaID,
		&i.TratadoPor,
		&i.TratadoEm,
		&i.OrigemIp,
		&i.CriadoEm,
	)
	return i, err
}

const contarTicketsAbertos = `-- name: ContarTicketsAbertos :one
SELECT count(*) FROM tickets WHERE status = 'aberto'
`

func (q *Queries) ContarTicketsAbertos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarTicketsAbertos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarTicket = `-- name: CriarTicket :one
INSERT INTO tickets (solicitante_nome, titulo, descricao, prioridade, origem_ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, numero, solicitante_nome, titulo, descricao, prioridade, status, tarefa_id, tratado_por, tratado_em, origem_ip, criado_em
`

type CriarTicketParams struct {
	SolicitanteNome string `json:"solicitante_nome"`
	Titulo          string `json:"titulo"`
	Descricao       string `json:"descricao"`
	Prioridade      string `json:"prioridade"`
	OrigemIp        string `json:"origem_ip"`
}

func (q *Queries) CriarTicket(ctx context.Context, arg CriarTicketParams) (Tickets, error) {
	row := q.db.QueryRow(ctx, criarTicket,
		arg.SolicitanteNome,
		arg.Titulo,
		arg.Descricao,
		arg.Prioridade,
		arg.OrigemIp,
	)
	var i Tickets
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.SolicitanteNome,
		&i.Titulo,
		&i.Descricao,
		&i.Prioridade,
		&i.Status,
		&i.TarefaID,
		&i.TratadoPor,
		&i.TratadoEm,
		&i.OrigemIp,
		&i.CriadoEm,
	)
	return i, err
}

const listarTickets = `-- name: ListarTickets :many
SELECT
    tk.id, tk.numero, tk.solicitante_nome, tk.titulo, tk.descricao,
    tk.prioridade, tk.status, tk.tarefa_id, tk.tratado_em, tk.criado_em,
    u.nome AS tratado_por_nome,
    ta.status AS tarefa_status
FROM tickets tk
LEFT JOIN usuarios u ON u.id = tk.tratado_por
LEFT JOIN tarefas ta ON ta.id = tk.tarefa_id
WHERE ($1::text IS NULL OR tk.status = $1)
ORDER BY
    CASE WHEN tk.status = 'aberto' THEN 0 ELSE 1 END,
    CASE WHEN tk.status = 'aberto' THEN
        CASE tk.prioridade WHEN 'alta' THEN 1 WHEN 'media' THEN 2 ELSE 3 END
    ELSE 0 END,
    CASE WHEN tk.status = 'aberto' THEN tk.criado_em END ASC,
    tk.tratado_em DESC NULLS LAST,
    tk.criado_em DESC
LIMIT 200
`

type ListarTicketsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Numero          int64              `json:"numero"`
	SolicitanteNome string             `json:"solicitante_nome"`
	Titulo          string             `json:"titulo"`
	Descricao       string             `json:"descricao"`
	Prioridade      string             `json:"prioridade"`
	Status          string             `json:"status"`
	TarefaID        pgtype.UUID        `json:"tarefa_id"`
	TratadoEm       pgtype.Timestamptz `json:"tratado_em"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	TratadoPorNome  pgtype.Text        `json:"tratado_por_nome"`
	TarefaStatus    pgtype.Text        `json:"tarefa_status"`
}

func (q *Queries) ListarTickets(ctx context.Context, status pgtype.Text) ([]ListarTicketsRow, error) {
	rows, err := q.db.Query(ctx, listarTickets, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTicketsRow
	for rows.Next() {
		var i ListarTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.SolicitanteNome,
			&i.Titulo,
			&i.Descricao,
			&i.Prioridade,
			&i.Status,
			&i.TarefaID,
			&i.TratadoEm,
			&i.CriadoEm,
			&i.TratadoPorNome,
			&i.TarefaStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarTicketTratado = `-- name: MarcarTicketTratado :one
UPDATE tickets
SET status = $2, tarefa_id = $3, tratado_por = $4, tratado_em = now()
WHERE id = $1
RETURNING id, numero, solicitante_nome, titulo, descricao, prioridade, status, tarefa_id, tratado_por, tratado_em, origem_ip, criado_em
`

type MarcarTicketTratadoParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	TarefaID   pgtype.UUID `json:"tarefa_id"`
	TratadoPor pgtype.UUID `json:"tratado_por"`
}

func (q *Queries) MarcarTicketTratado(ctx context.Context, arg MarcarTicketTratadoParams) (Tickets, error) {
	row := q.db.QueryRow(ctx, marcarTicketTratado,
		arg.ID,
		arg.Status,
		arg.TarefaID,
		arg.TratadoPor,
	)
	var i Tickets
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.SolicitanteNome,
		&i.Titulo,
		&i.Descricao,
		&i.Prioridade,
		&i.Status,
		&i.TarefaID,
		&i.TratadoPor,
		&i.TratadoEm,
		&i.OrigemIp,
		&i.CriadoEm,
	)
	return i, err
}
