// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarPin = `-- name: AtualizarPin :one
UPDATE usuarios
SET pin_hash = $2
WHERE id = $1
RETURNING id
`

type AtualizarPinParams struct {
	ID      pgtype.UUID `json:"id"`
	PinHash string      `json:"pin_hash"`
}

func (q *Queries) AtualizarPin(ctx context.Context, arg AtualizarPinParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, atualizarPin, arg.ID, arg.PinHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const atualizarProprioPin = `-- name: AtualizarProprioPin :exec
UPDATE usuarios
SET pin_hash = $2, deve_trocar_pin = false, tentativas_falhas = 0, bloqueado_ate = NULL, bloqueios = 0
WHERE id = $1
`

type AtualizarProprioPinParams struct {
	ID      pgtype.UUID `json:"id"`
	PinHash string      `json:"pin_hash"`
}

// Troca feita pelo próprio usuário: cumpre a troca obrigatória e zera as tentativas
func (q *Queries) AtualizarProprioPin(ctx context.Context, arg AtualizarProprioPinParams) error {
	_, err := q.db.Exec(ctx, atualizarProprioPin, arg.ID, arg.PinHash)
	return err
}

const atualizarTemaUsuario = `-- name: AtualizarTemaUsuario :one
UPDATE usuarios
SET tema = $2
WHERE id = $1
RETURNING id, tema
`

type AtualizarTemaUsuarioParams struct {
	ID   pgtype.UUID `json:"id"`
	Tema string      `json:"tema"`
}

type AtualizarTemaUsuarioRow struct {
	ID   pgtype.UUID `json:"id"`
	Tema string      `json:"tema"`
}

func (q *Queries) AtualizarTemaUsuario(ctx context.Context, arg AtualizarTemaUsuarioParams) (AtualizarTemaUsuarioRow, error) {
	row := q.db.QueryRow(ctx, atualizarTemaUsuario, arg.ID, arg.Tema)
	var i AtualizarTemaUsuarioRow
	err := row.Scan(&i.ID, &i.Tema)
	return i, err
}

const atualizarUsuario = `-- name: AtualizarUsuario :one
UPDATE usuarios
SET nome = $2, cor = $3, papel = $4, ativo = $5
WHERE id = $1
RETURNING id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
`

type AtualizarUsuarioParams struct {
	ID    pgtype.UUID `json:"id"`
	Nome  string      `json:"nome"`
	Cor   string      `json:"cor"`
	Papel string      `json:"papel"`
	Ativo bool        `json:"ativo"`
}

type AtualizarUsuarioRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (AtualizarUsuarioRow, error) {
	row := q.db.QueryRow(ctx, atualizarUsuario,
		arg.ID,
		arg.Nome,
		arg.Cor,
		arg.Papel,
		arg.Ativo,
	)
	var i AtualizarUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const buscarUsuarioPorID = `-- name: BuscarUsuarioPorID :one
SELECT id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
FROM usuarios
WHERE id = $1
`

type BuscarUsuarioPorIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) BuscarUsuarioPorID(ctx context.Context, id pgtype.UUID) (BuscarUsuarioPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorID, id)
	var i BuscarUsuarioPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const buscarUsuarioPorIDComPin = `-- name: BuscarUsuarioPorIDComPin :one
SELECT id, nome, cor, pin_hash, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
FROM usuarios
WHERE id = $1
`

type BuscarUsuarioPorIDComPinRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	PinHash          string             `json:"pin_hash"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) BuscarUsuarioPorIDComPin(ctx context.Context, id pgtype.UUID) (BuscarUsuarioPorIDComPinRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorIDComPin, id)
	var i BuscarUsuarioPorIDComPinRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.PinHash,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const contarAdminsAtivos = `-- name: ContarAdminsAtivos :one
SELECT count(*)
FROM usuarios
WHERE papel = 'admin' AND ativo = true
`

func (q *Queries) ContarAdminsAtivos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarAdminsAtivos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarUsuarios = `-- name: ContarUsuarios :one
SELECT count(*)
FROM usuarios
`

func (q *Queries) ContarUsuarios(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarUsuarios)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarUsuario = `-- name: CriarUsuario :one
INSERT INTO usuarios (nome, cor, pin_hash, papel, ativo)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
`

type CriarUsuarioParams struct {
	Nome    string `json:"nome"`
	Cor     string `json:"cor"`
	PinHash string `json:"pin_hash"`
	Papel   string `json:"papel"`
	Ativo   bool   `json:"ativo"`
}

type CriarUsuarioRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error) {
	row := q.db.QueryRow(ctx, criarUsuario,
		arg.Nome,
		arg.Cor,
		arg.PinHash,
		arg.Papel,
		arg.Ativo,
	)
	var i CriarUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const desbloquearUsuario = `-- name: DesbloquearUsuario :one
UPDATE usuarios
SET tentativas_falhas = 0, bloqueado_ate = NULL, bloqueios = 0
WHERE id = $1
RETURNING id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
`

type DesbloquearUsuarioRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) DesbloquearUsuario(ctx context.Context, id pgtype.UUID) (DesbloquearUsuarioRow, error) {
	row := q.db.QueryRow(ctx, desbloquearUsuario, id)
	var i DesbloquearUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const listarTodosUsuarios = `-- name: ListarTodosUsuarios :many
SELECT u.id, u.nome, u.cor, u.papel, u.ativo, u.tentativas_falhas, u.bloqueado_ate, u.criado_em, u.tema,
       f.atualizado_em AS foto_atualizada_em
FROM usuarios u
LEFT JOIN usuario_fotos f ON f.usuario_id = u.id
ORDER BY u.nome ASC
`

type ListarTodosUsuariosRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
	FotoAtualizadaEm pgtype.Timestamptz `json:"foto_atualizada_em"`
}

func (q *Queries) ListarTodosUsuarios(ctx context.Context) ([]ListarTodosUsuariosRow, error) {
	rows, err := q.db.Query(ctx, listarTodosUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTodosUsuariosRow
	for rows.Next() {
		var i ListarTodosUsuariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Cor,
			&i.Papel,
			&i.Ativo,
			&i.TentativasFalhas,
			&i.BloqueadoAte,
			&i.CriadoEm,
			&i.Tema,
			&i.FotoAtualizadaEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuariosAtivos = `-- name: ListarUsuariosAtivos :many
SELECT u.id, u.nome, u.cor, f.atualizado_em AS foto_atualizada_em
FROM usuarios u
LEFT JOIN usuario_fotos f ON f.usuario_id = u.id
WHERE u.ativo = true
ORDER BY u.nome ASC
`

type ListarUsuariosAtivosRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	FotoAtualizadaEm pgtype.Timestamptz `json:"foto_atualizada_em"`
}

func (q *Queries) ListarUsuariosAtivos(ctx context.Context) ([]ListarUsuariosAtivosRow, error) {
	rows, err := q.db.Query(ctx, listarUsuariosAtivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarUsuariosAtivosRow
	for rows.Next() {
		var i ListarUsuariosAtivosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Cor,
			&i.FotoAtualizadaEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarTrocaPinObrigatoria = `-- name: MarcarTrocaPinObrigatoria :exec
UPDATE usuarios
SET deve_trocar_pin = true
WHERE id = $1
`

func (q *Queries) MarcarTrocaPinObrigatoria(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, marcarTrocaPinObrigatoria, id)
	return err
}

const obterFotoUsuario = `-- name: ObterFotoUsuario :one
SELECT f.conteudo, f.mime, f.atualizado_em, u.ativo AS usuario_ativo
FROM usuario_fotos f
JOIN usuarios u ON u.id = f.usuario_id
WHERE f.usuario_id = $1
`

type ObterFotoUsuarioRow struct {
	Conteudo     []byte             `json:"conteudo"`
	Mime         string             `json:"mime"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
	UsuarioAtivo bool               `json:"usuario_ativo"`
}

func (q *Queries) ObterFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) (ObterFotoUsuarioRow, error) {
	row := q.db.QueryRow(ctx, obterFotoUsuario, usuarioID)
	var i ObterFotoUsuarioRow
	err := row.Scan(
		&i.Conteudo,
		&i.Mime,
		&i.AtualizadoEm,
		&i.UsuarioAtivo,
	)
	return i, err
}

const obterVersaoFotoUsuario = `-- name: ObterVersaoFotoUsuario :one
SELECT atualizado_em
FROM usuario_fotos
WHERE usuario_id = $1
`

func (q *Queries) ObterVersaoFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, obterVersaoFotoUsuario, usuarioID)
	var atualizado_em pgtype.Timestamptz
	err := row.Scan(&atualizado_em)
	return atualizado_em, err
}

const removerFotoUsuario = `-- name: RemoverFotoUsuario :exec
DELETE FROM usuario_fotos
WHERE usuario_id = $1
`

func (q *Queries) RemoverFotoUsuario(ctx context.Context, usuarioID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removerFotoUsuario, usuarioID)
	return err
}

const reservarTentativaPin = `-- name: ReservarTentativaPin :one
UPDATE usuarios
SET tentativas_falhas = CASE
        WHEN ultima_tentativa_em IS NULL OR ultima_tentativa_em < now() - interval '15 minutes'
             OR bloqueado_ate IS NOT NULL THEN 1
        ELSE tentativas_falhas + 1
    END,
    bloqueado_ate = CASE
        WHEN ultima_tentativa_em >= now() - interval '15 minutes' AND bloqueado_ate IS NULL
             AND tentativas_falhas + 1 >= 5
            THEN now() + least(interval '5 minutes' * power(3, bloqueios), interval '1 hour')
    END,
    bloqueios = CASE
        WHEN ultima_tentativa_em >= now() - interval '15 minutes' AND bloqueado_ate IS NULL
             AND tentativas_falhas + 1 >= 5
            THEN bloqueios + 1
        ELSE bloqueios
    END,
    ultima_tentativa_em = now()
WHERE id = $1 AND ativo = true AND (bloqueado_ate IS NULL OR bloqueado_ate <= now())
RETURNING id, nome, cor, pin_hash, papel, tema, bloqueado_ate, deve_trocar_pin
`

type ReservarTentativaPinRow struct {
	ID            pgtype.UUID        `json:"id"`
	Nome          string             `json:"nome"`
	Cor           string             `json:"cor"`
	PinHash       string             `json:"pin_hash"`
	Papel         string             `json:"papel"`
	Tema          string             `json:"tema"`
	BloqueadoAte  pgtype.Timestamptz `json:"bloqueado_ate"`
	DeveTrocarPin bool               `json:"deve_trocar_pin"`
}

// Conta a tentativa ANTES de comparar o PIN, numa única instrução atômica:
// requisições simultâneas não passam juntas pela checagem de bloqueio.
// Sem linha retornada = usuário inexistente, inativo ou bloqueado.
// A contagem recomeça após 15 min sem tentativas ou ao fim de um bloqueio
// (o WHERE garante que bloqueado_ate, se preenchido, já expirou). A 5ª
// tentativa seguida bloqueia por 5 min, 15 min, 45 min e depois 1 h.
func (q *Queries) ReservarTentativaPin(ctx context.Context, id pgtype.UUID) (ReservarTentativaPinRow, error) {
	row := q.db.QueryRow(ctx, reservarTentativaPin, id)
	var i ReservarTentativaPinRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.PinHash,
		&i.Papel,
		&i.Tema,
		&i.BloqueadoAte,
		&i.DeveTrocarPin,
	)
	return i, err
}

const salvarFotoUsuario = `-- name: SalvarFotoUsuario :one
INSERT INTO usuario_fotos (usuario_id, conteudo, mime, atualizado_em)
VALUES ($1, $2, $3, now())
ON CONFLICT (usuario_id) DO UPDATE
SET conteudo = EXCLUDED.conteudo, mime = EXCLUDED.mime, atualizado_em = now()
RETURNING atualizado_em
`

type SalvarFotoUsuarioParams struct {
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Conteudo  []byte      `json:"conteudo"`
	Mime      string      `json:"mime"`
}

func (q *Queries) SalvarFotoUsuario(ctx context.Context, arg SalvarFotoUsuarioParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, salvarFotoUsuario, arg.UsuarioID, arg.Conteudo, arg.Mime)
	var atualizado_em pgtype.Timestamptz
	err := row.Scan(&atualizado_em)
	return atualizado_em, err
}

const zerarTentativasFalhas = `-- name: ZerarTentativasFalhas :exec
UPDATE usuarios
SET tentativas_falhas = 0, bloqueado_ate = NULL, bloqueios = 0
WHERE id = $1
`

func (q *Queries) ZerarTentativasFalhas(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, zerarTentativasFalhas, id)
	return err
}
