// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarPin = `-- name: AtualizarPin :one
UPDATE usuarios
SET pin_hash = $2
WHERE id = $1
RETURNING id
`

type AtualizarPinParams struct {
	ID      pgtype.UUID `json:"id"`
	PinHash string      `json:"pin_hash"`
}

func (q *Queries) AtualizarPin(ctx context.Context, arg AtualizarPinParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, atualizarPin, arg.ID, arg.PinHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const atualizarTemaUsuario = `-- name: AtualizarTemaUsuario :one
UPDATE usuarios
SET tema = $2
WHERE id = $1
RETURNING id, tema
`

type AtualizarTemaUsuarioParams struct {
	ID   pgtype.UUID `json:"id"`
	Tema string      `json:"tema"`
}

type AtualizarTemaUsuarioRow struct {
	ID   pgtype.UUID `json:"id"`
	Tema string      `json:"tema"`
}

func (q *Queries) AtualizarTemaUsuario(ctx context.Context, arg AtualizarTemaUsuarioParams) (AtualizarTemaUsuarioRow, error) {
	row := q.db.QueryRow(ctx, atualizarTemaUsuario, arg.ID, arg.Tema)
	var i AtualizarTemaUsuarioRow
	err := row.Scan(&i.ID, &i.Tema)
	return i, err
}

const atualizarUsuario = `-- name: AtualizarUsuario :one
UPDATE usuarios
SET nome = $2, cor = $3, papel = $4, ativo = $5
WHERE id = $1
RETURNING id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
`

type AtualizarUsuarioParams struct {
	ID    pgtype.UUID `json:"id"`
	Nome  string      `json:"nome"`
	Cor   string      `json:"cor"`
	Papel string      `json:"papel"`
	Ativo bool        `json:"ativo"`
}

type AtualizarUsuarioRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) AtualizarUsuario(ctx context.Context, arg AtualizarUsuarioParams) (AtualizarUsuarioRow, error) {
	row := q.db.QueryRow(ctx, atualizarUsuario,
		arg.ID,
		arg.Nome,
		arg.Cor,
		arg.Papel,
		arg.Ativo,
	)
	var i AtualizarUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const buscarUsuarioPorID = `-- name: BuscarUsuarioPorID :one
SELECT id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
FROM usuarios
WHERE id = $1
`

type BuscarUsuarioPorIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) BuscarUsuarioPorID(ctx context.Context, id pgtype.UUID) (BuscarUsuarioPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorID, id)
	var i BuscarUsuarioPorIDRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const buscarUsuarioPorIDComPin = `-- name: BuscarUsuarioPorIDComPin :one
SELECT id, nome, cor, pin_hash, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
FROM usuarios
WHERE id = $1
`

func (q *Queries) BuscarUsuarioPorIDComPin(ctx context.Context, id pgtype.UUID) (Usuarios, error) {
	row := q.db.QueryRow(ctx, buscarUsuarioPorIDComPin, id)
	var i Usuarios
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.PinHash,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const contarAdminsAtivos = `-- name: ContarAdminsAtivos :one
SELECT count(*)
FROM usuarios
WHERE papel = 'admin' AND ativo = true
`

func (q *Queries) ContarAdminsAtivos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarAdminsAtivos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarUsuarios = `-- name: ContarUsuarios :one
SELECT count(*)
FROM usuarios
`

func (q *Queries) ContarUsuarios(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarUsuarios)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarUsuario = `-- name: CriarUsuario :one
INSERT INTO usuarios (nome, cor, pin_hash, papel, ativo)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
`

type CriarUsuarioParams struct {
	Nome    string `json:"nome"`
	Cor     string `json:"cor"`
	PinHash string `json:"pin_hash"`
	Papel   string `json:"papel"`
	Ativo   bool   `json:"ativo"`
}

type CriarUsuarioRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) CriarUsuario(ctx context.Context, arg CriarUsuarioParams) (CriarUsuarioRow, error) {
	row := q.db.QueryRow(ctx, criarUsuario,
		arg.Nome,
		arg.Cor,
		arg.PinHash,
		arg.Papel,
		arg.Ativo,
	)
	var i CriarUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const desbloquearUsuario = `-- name: DesbloquearUsuario :one
UPDATE usuarios
SET tentativas_falhas = 0, bloqueado_ate = NULL
WHERE id = $1
RETURNING id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
`

type DesbloquearUsuarioRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) DesbloquearUsuario(ctx context.Context, id pgtype.UUID) (DesbloquearUsuarioRow, error) {
	row := q.db.QueryRow(ctx, desbloquearUsuario, id)
	var i DesbloquearUsuarioRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cor,
		&i.Papel,
		&i.Ativo,
		&i.TentativasFalhas,
		&i.BloqueadoAte,
		&i.CriadoEm,
		&i.Tema,
	)
	return i, err
}

const incrementarTentativasFalhas = `-- name: IncrementarTentativasFalhas :one
UPDATE usuarios
SET tentativas_falhas = tentativas_falhas + 1,
    bloqueado_ate = CASE 
        WHEN tentativas_falhas + 1 >= 5 THEN now() + interval '5 minutes'
        ELSE bloqueado_ate
    END
WHERE id = $1
RETURNING tentativas_falhas, bloqueado_ate
`

type IncrementarTentativasFalhasRow struct {
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
}

func (q *Queries) IncrementarTentativasFalhas(ctx context.Context, id pgtype.UUID) (IncrementarTentativasFalhasRow, error) {
	row := q.db.QueryRow(ctx, incrementarTentativasFalhas, id)
	var i IncrementarTentativasFalhasRow
	err := row.Scan(&i.TentativasFalhas, &i.BloqueadoAte)
	return i, err
}

const listarTodosUsuarios = `-- name: ListarTodosUsuarios :many
SELECT id, nome, cor, papel, ativo, tentativas_falhas, bloqueado_ate, criado_em, tema
FROM usuarios
ORDER BY nome ASC
`

type ListarTodosUsuariosRow struct {
	ID               pgtype.UUID        `json:"id"`
	Nome             string             `json:"nome"`
	Cor              string             `json:"cor"`
	Papel            string             `json:"papel"`
	Ativo            bool               `json:"ativo"`
	TentativasFalhas int32              `json:"tentativas_falhas"`
	BloqueadoAte     pgtype.Timestamptz `json:"bloqueado_ate"`
	CriadoEm         pgtype.Timestamptz `json:"criado_em"`
	Tema             string             `json:"tema"`
}

func (q *Queries) ListarTodosUsuarios(ctx context.Context) ([]ListarTodosUsuariosRow, error) {
	rows, err := q.db.Query(ctx, listarTodosUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarTodosUsuariosRow
	for rows.Next() {
		var i ListarTodosUsuariosRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Cor,
			&i.Papel,
			&i.Ativo,
			&i.TentativasFalhas,
			&i.BloqueadoAte,
			&i.CriadoEm,
			&i.Tema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuariosAtivos = `-- name: ListarUsuariosAtivos :many
SELECT id, nome, cor
FROM usuarios
WHERE ativo = true
ORDER BY nome ASC
`

type ListarUsuariosAtivosRow struct {
	ID   pgtype.UUID `json:"id"`
	Nome string      `json:"nome"`
	Cor  string      `json:"cor"`
}

func (q *Queries) ListarUsuariosAtivos(ctx context.Context) ([]ListarUsuariosAtivosRow, error) {
	rows, err := q.db.Query(ctx, listarUsuariosAtivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarUsuariosAtivosRow
	for rows.Next() {
		var i ListarUsuariosAtivosRow
		if err := rows.Scan(&i.ID, &i.Nome, &i.Cor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const zerarTentativasFalhas = `-- name: ZerarTentativasFalhas :exec
UPDATE usuarios
SET tentativas_falhas = 0, bloqueado_ate = NULL
WHERE id = $1
`

func (q *Queries) ZerarTentativasFalhas(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, zerarTentativasFalhas, id)
	return err
}
